### ISSUE TITLE
Default Sia directory

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#1070]
It would be useful if Sia defaulted to a standard directory instead of defaulting to the current directory on startup if the `-d` or `--sia-directory` flags are not specified.

We could follow Bitcoin and set the default directory to:
`~/.sia` for Linux
`~/Library/Application Support/Sia` for OS X
`%APPDATA%\Sia` for Windows

**Comment by Fornax96** [comment]
Please don't put the data directly in the home directory, my home dir is already bloated enough with all those spec-breaking steam games. You can use `~/.local/share/sia` instead. It's the recommended location for app data according to the freedesktop specification. 
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

Also, ubuntu doesn't set the XDG variables by default, it's recommended to fallback to `$HOME/.local/share`: http://askubuntu.com/questions/538526/is-home-local-share-the-default-value-for-xdg-data-home-in-ubuntu-14-04

**Comment by DavidVorick** [comment]
I will also mention that last time we had sia default to a specific directory people lost millions of coins because multiple instances of Sia started overwriting the same files in incompatible ways.

The wallet today is much, much safer, so the result wouldn't be millions of coins lost, but I'm sure there would be headaches nonetheless.

**Comment by Fornax96** [comment]
You could append the wallet version number to the wallet file, and then add a button or API call to import the previous version wallet. That may not always be necessary, since the wallet code doesn't change with every version.
Maybe you could even add a different versioning scheme for wallet code so only incompatible wallets need to be imported.

**Comment by DavidVorick** [comment]
The real problem I think came from people having multiple running at a time, especially when trying to transfer coins from one to the other.

I was thinking we could have a different directory for each port. But then if you want to launch siad on a new port number you'll either need to copy it, or you won't have your data.

We're already pretty overwhelmed with the UX stuff just trying to figure out how to make the API secure. We might make siad installable at some point, but I think our time is best spent on the other UX stuff for now.

**Comment by VoidingWarranties** [comment]
@DavidVorick #1225 would prevent multiple instances using the same directory and corrupting the files.

**Comment by DavidVorick** [comment]
I think for the time being we want to keep siad portable, this is especially doable since we have in-place updates.

**Comment by winsvega** [comment]
so is it possible to set --datadir for sia?

**Comment by cies** [comment]
It does not even respond well to `--help` :)  Other wise cool piece of software.

I have move the dir to /usr/local and then made a symlink to that from its orig location.
