### ISSUE TITLE
files in different folders on host

### ISSUE THREAD

**Issue by poiuty** [NebulousLabs/Sia#1075]
All files in one folder
```
# ls host/
1      12660  13598  15223  17227  17472  7672	8070  8438  8593  8765	8977  9281
10107  12667  13599  15224  17228  17474  7673	8071  8439  8594  8766	8978  9282
10108  12671  13600  15225  17229  17476  7674	8072  8440  8595  8767	8979  9283
10109  12672  13602  15226  17230  17478  7675	8073  8441  8596  8768	8980  9284
10110  12674  13603  15270  17231  17479  7676	8074  8442  8597  8769	8981  9285
....
many files
```

Let's put  files in different folders (better performance)
```
# ls host/
aa/
ab/
ad/
ac/
...
```

**Comment by iwanbk** [comment]
hi all, i offer my help on this.

We group it by integer representation of first N bytes of contract ID.

For example, lets say we choose N = 3 and integer values of first N bytes are = 10, 5, and 30.
Filename's full path will be: host/10/5/30/filename.

I am still not sure the exact value of N, maybe we can start with 20.
If N = 20, one directory will only have max of 4096 files.

Let me know if it is OK, i will implement and submit a PR.

**Comment by DavidVorick** [comment]
host is being completely redesigned. I definitely appreciate that you guys are looking into this, but please hold off until the `renter-host-upgrades` branch has been merged into master - the implementation is completely different.

As it were, it has even more files. The new host creates a file per sector, so your folder is going to look a lot busier. There will be potentially hundreds of thousands of files in each folder.

@poiuty can you explain why there is better performance by creating a hierarchy instead of having everything in one folder? I was under the impression that it wouldn't be an issue until you hit tens of millions of files.

The new host should be ready by the end of the week, we've been working on it for a few months. I think some of the same concerns will apply, but it will be better if you hold off on writing code until the merge.

**Comment by poiuty** [comment]
@DavidVorick 
>  I was under the impression that it wouldn't be an issue until you hit tens of millions of files.
I'm talking about this. I setup host for test. And get 1GB data => 1761 files.
So, perhaps 1000GB => 1761000 files, and 20Tb =>  20*1761000 => 35220000 files.
I would be happy to place a lot of files in different folders than to keep them all in one.

**Comment by Fornax96** [comment]
Is it really a serious problem? I thought modern filesystems don't care whether you put 10 or 10 million files in one directory. As far as I know the only program suffering from it is the file manager which has to render them all. But since you shouldn't have to open the host dir in your file manager anyway it shouldn't matter.

For example, for testing pixeldrain.com I have multiple directories with 100k's of files in them, but the access latency never suffers. But maybe that's just because brtfs is better optimized for this. The website itself runs on ext4 and currently has 50k files on it in one directory and access speeds are great.

**Comment by DavidVorick** [comment]
@fornax96 my understanding is that the filesystem will start to suffer once it no longer fits into memory. 1GB of RAM can hold probably between 1 million and 50 million files, depending on how well it's built. A host with 20TB could be pretty reasonably expected to have 16GB of RAM, and on Sia would end up with about 15 million files at full capacity.

I'm guessing that at 16GB of RAM you'd be able manage about 80TB of data. But we haven't run any sort of stress tests on this yet, that'll come after 1.0.

**Comment by DavidVorick** [comment]
@iwanbk @poiuty I've split out the storage management into a separate package. It should be easier to understand and modify the code, and there should be a lower chance of disrupting something else now that I've decoupled the storage management from the actual host.

There's also a nice interface, so if you want to make a completely different storage manager of your own design, all you have to do is satisfy the interface. We don't plan on spending a lot of time optimizing the storage manager ourselves in the near future, but if that's a problem you guys want to tackle we'd welcome the contributions.

Relevant interface: https://github.com/NebulousLabs/Sia/blob/master/modules/storagemanager.go
My implementation: https://github.com/NebulousLabs/Sia/tree/master/modules/host/storagemanager

Feel free to PR any changes that you think would be improvements.

**Comment by DavidVorick** [comment]
this is being closed for now, as nobody has yet submitted performance issues. I'm sure the storagemanager will need additional improvements to hit 10TB+ smoothly, but thus far it is not necessary.
