### ISSUE TITLE
Best Unit?

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#1109]
Should we displace prices in GB / Mo, or TB / Mo?

19,000 SC / TB / Mo is easier for bulk users, because they typically measure their data in TB.

But, 19 SC / GB / Mo seems more... relatable? 19,000 is a big number. But we should also consider a future where SC is 3x as valuable and the price is 1/2. Now you're looking at prices of 2 and 3 SC / GB / Mo, which means you have very little precision.

But, 2,000 SC / TB / Mo still seems like a huge price. I don't think we want people advertising that they are that expensive. It makes the system feel expensive, which is not really the goal.

I'm uncertain.

**Comment by VoidingWarranties** [comment]
Precision will be more important once people start using other tools to price their storage.

Can you specify a decimal price?

**Comment by pmknutsen** [comment]
Is this just for display, or also entry? If the latter (as well) you may
want to consider the consequences of data entry errors.

For instance, entering 19 SC/TB is a more severe error than entering 19000
SC/GB, since the former is likely to have an immediate practical effect
while the latter will have no effect (because the storage will be orders of
magnitude more expensive than the competition).
