### ISSUE TITLE
Host announces automatically regardless of `acceptingcontracts`

### ISSUE THREAD

**Issue by johnathanhowell** [NebulousLabs/Sia#1212]
This can cause unexpected outgoing announcement transactions to appear in the wallet.

**Comment by DavidVorick** [comment]
I am not sure that I agree that this is a bug. The host should be serving contracts and responding to download requests even if it is no longer accepting contracts. It should also be continuously updating its ip address so that renters can update their databases in the event that the host ip address changes.

If you don't want the host responding to requests, the best thing to do is probably to disable the host.

I think it would be pretty easy to start with no modules, but then have a command `siac start host` or `siac start miner` to spin up new modules as you desire. Especially now that there is clean shutdown, we can spin them down as well.

**Comment by VoidingWarranties** [comment]
From my understanding the current behavior is that when you start up Sia for the first time the host will announce as soon as it discovers its address, even if `acceptingcontracts` is false.

Since the host is a default module, this has resulted in the majority of Sia nodes announcing themselves as hosts, even though many have no intention of being a host. This is polluting the hostdb with hosts that aren't actually hosts, and is also unnecessarily spending coins announcing.

The simplest solution is to remove the host as a default module. A more complete solution would be to only automatically announce if you have open contracts.

**Comment by DavidVorick** [comment]
Ah. So it looks like we've got more hosts than we actually do, because most of them are not accepting contracts.

Another thing that the hostdb should be doing is not feeding hosts through `RandomHosts()` if they are not accepting contracts.

**Comment by lukechampine** [comment]
why would the host announce as soon as it discovers its address??
don't you need money to announce anyway? The host shouldn't spend your money if you haven't specifically authorized it to do so.

**Comment by DavidVorick** [comment]
Makes sense.

**Comment by DavidVorick** [comment]
Ok, so one reason that I left the host to continue announcing even if you are not accepting contracts is that you want renters to be able to find you by your public key so they can do downloading.

So I think announcing should only be ignored if you both have 0 contracts and are not accepting new ones. If you have a contract, you should be letting the corresponding renter know where you can be contacted.

**Comment by VoidingWarranties** [comment]
Closed in #1267
