### ISSUE TITLE
Wallet should not accept sending addresses without a checksum

### ISSUE THREAD

**Issue by johnathanhowell** [NebulousLabs/Sia#1232]

**Comment by lukechampine** [comment]
can you describe this a bit better? What's the current behavior vs. desired behavior?

**Comment by DavidVorick** [comment]
When you send money through the wallet api using a destination that is only 64 characters, the destination is accepted. 64 character addresses do not have a checksum, and therefore are vulnerable to incorrectness.

The wallet api should return an error when getting an address of insufficient length. All addresses exposed to the user have had checksums since v0.4.0, there is no longer a need to support sending money to 64 byte addresses. People still using v0.3.3.x should upgrade if they want to keep receiving money.
