### ISSUE TITLE
Windows client - cannot create new folder for sharing

### ISSUE THREAD

**Issue by phobosq** [NebulousLabs/Sia#1295]
On Windows, when issuing following command:
P:\Misc\SC\wallet>siac host folder add p:\misc\sc\share\1 100GB
Could not add folder: symlink p:\misc\sc\share\1 host\storagemanager\86d0faa1: Klient nie ma wymaganych uprawnień. (You do not have sufficient privilege to perform this operation.)

I can do mklink /J host\storagemanager\86d0faa1 p:\misc\sc\share\1 and I will get a directory link created in host\storagemanager folder, but there is no shared space in Sia client. I suspect it's Windows specific.

**Comment by lukechampine** [comment]
Indeed. You need admin privileges in order to be a host on Windows. The easiest way to do this is to run `siad` from an Admin command prompt.
Unfortunately, this doesn't seem like an easy fix on the backend. It is a high priority, but it won't make the 1.0 release.

c.f. https://github.com/NebulousLabs/Sia/issues/1173
