### ISSUE TITLE
Make `gateway.Broadcast` a nonblocking call

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#1367]
@VoidingWarranties 

Everywhere that `gateway.Broadcast` is used in our production code (and even most of the testing code), it is called with `go gateway.Broadcast`. To me that's a pretty strong indicator that `Broadcast` should be a nonblocking function, especially because the purpose of the gateway is to abstract away the network stuff.

Sia is a flood network, which means that you should never be in a position where you have to wait until you know something had broadcasted before continuing with your logic. Even if `Broadcast` returns, you don't know which peers ended up getting the object and you don't know if those peers are the ones that you were targeting. I don't see a use case where you would want to block until `Broadcast` has completed.

It is my understanding that part of the reason was to make testing easier. But, now that we have the `Flush()` call, we can just call `gateway.Flush()` to know that the broadcast has finished during testing.

There is another issue related to testing here. In a broad ecosystem test with flushing, there's not currently a way to be certain that the gateway has broadcasted a block that I've given to the consensus set:

``` go
cs.AcceptBlock(b) // give the consensus set a block
cs.Flush() // Allow it to finish processing the block

// ERROR: because the consensus set calls `go g.Broadcast`, 
// we don't know if that goroutine has started operating yet.
// But if Broadcast were nonblocking in the gateway, the
// consensus set would not need to call `go g.Broadcast`, which
// means that we could guarantee that `g.Add` had been called
// on the broadcast code before cs.Flush() completed, which
// means that g.Flush() *would* guarantee that the broadcast
// had completed.
g.Flush() 
```

**Comment by lukechampine** [comment]
APIs should be synchronous so that the caller can decide whether to call them in a goroutine or not. See https://talks.golang.org/2013/bestpractices.slide#25

It bothers me that we are now coding around `Flush`. I don't like `Flush`, especially as an exported method. It's a hack that was introduced solely to make some tests easier to write.
The deeper issue, I think, is that our modules are too smart. They have background threads that arbitrarily mutate state, call other modules' methods, and spawn more threads; they register callbacks with other modules in four different ways (`ConsensusSetSubscribe`, `TransactionPoolSubscribe`, `RegisterRPC`, `RegisterConnectCall`); and simultaneously, their methods are being called by API requests. The end result is that we have very limited means for introspecting what Sia (as a whole) is doing at any given time, or forcing it to operate in a deterministic way. We have to resort to things like `Flush` because we have no other way to control our goroutines.

There are only three sources of events:
- the user (API calls, interrupt signals)
- peers (dialing, RPCs)
- time (repair loop, hostdb scanning)

What would Sia look like if we handled all of these events in the same place? Modules would no longer be independent actors; they wouldn't do anything until you called a method. A lot of logic would be moved out of the modules and into a centralized controller. At the cost of managing all that complexity in one place, we'd have explicit control over the numerous interactions between modules. We could simulate a sequence of events and proceed to inspect the result without needing to worry about concurrency; after the calls complete, none of the modules will change further. In general, the philosophy of this approach is: _move concurrency as high up the call-stack as you can_.

I know we're in far too deep to realistically change this stuff. I'm not even convinced that my alternative a good idea -- I'm sure it would come with its own set of challenges and annoyances. I just needed to ~~get~~ flush that rant out of my system. :anger: :ok_hand:

**Comment by DavidVorick** [comment]
No worries about the rant, helps to keep everyone on the same page. Doesn't come across as attacking or defensive to me, Flush is a pretty big change that's needed to address shortcomings in our existing concurrency design.

I'm not exactly sure what you have in mind, but the picture I'm getting is of a large, prone-to-spaghettify codeset that handles all input into the Sia daemon. What happens when you want to add a new RPC? A new time-related operation? A new API call that the user can interact with? They all somehow go through this growing central controller that inevitably did not cover all use cases and was not designed nearly broad enough in the first place (simply because we don't have enough experience to make it so - Flush is a good example of how our existing module architecture was insufficient), and so as it grows in complexity we lose control of it and the ability to safely make changes to it, at the same time losing flexibility on what we can implement in the future.

To me a central controller for any concurrency patterns seems like something that would cause a massive amount of coupling between parts of the code. If every module is dependent on the controller, any changes to the controller affects every module. The way things are currently built, I can introduce a completely new concurrency paradigm such as Flush and we can introduce it incrementally. I don't think we could do that with the central controller - adding Flush would mean implementing it across modules at once before being able to deploy it.

Maybe I am not being generous enough, but there are very strong reasons to keep pieces of code as independent as possible, and I'm having trouble seeing a central controller that enables the level of independence our modules currently have.

I do see Flush as a shoehorn, if I were to start over I'd make sure that we could have sufficient introspection and control over the asynchrony of the modules, but I'd do it with calls like `Flush` - calls that you can make to modules individually to control their actions/progress and not with a central controller. I'm sure the result would be more elegant that the current flush call but controlling a set of modules would still likely require invoking concurrency controls on each of them separately.

> APIs should be synchronous so that the caller can decide whether to call them in a goroutine or not. See https://talks.golang.org/2013/bestpractices.slide#25

Yes, but the way `Broadcast` is currently implemented forces us to call it in a goroutine. And I don't think it's the same as something like `UploadFile` or `AcceptBlock`, because the result of the action is largely irrelevant to your state of being. It's not important to broadcast things in order, and it's not important to stall until a broadcast has been successful. There's also not much you can do if a broadcast fails, except perhaps by notifying the user. Any other actions that might be reasonable would very clearly fall within the bounds of the gateway anyway.

The specific concern I've got is that we can't implement clean shutdown / flushing / concurrency control  in the consensus set unless we block on those Broadcast calls (by using a `ThreadGroup`, not by blocking `AcceptBlock` or anything), which means during shutdown we'd need to wait for all open Broadcast calls to finish, and we wouldn't have a way of interrupting them.

The gateway does have a way of interrupting them. But you can't tell the gateway to close until the consensus set has closed, the consensus set will not close until the Broadcast returns. So you can't control that aspect of shutdown unless you add another function to allow the introspection.

-----

We really wouldn't be having many of these problems if we had all of the code in a single massive package. We could look at all the variables without creating getters, we could manipulate state directly, and we'd be sort of closer to the central controller design, but then we'd have a package that's like 20,000 lines of code. (simpler things like the encoding package and sync package could remain separate).

I've always worked very hard to keep functions as separate as possible, and I think the concurrency problems we are running into are just a part of that. 

I'll keep thinking on it, but in the meantime it seems to me like Flush will allow us to elevate our testing significantly without needing to make broad changes to the codebase (at least not all at once, anyway).

**Comment by DavidVorick** [comment]
So, thinking about this controller thing a bit more, I have an example which I think is pretty good. Let's treat this as a work-in-progress and try to design...

wait, I'm moving this to a new thread. Let's focus on `Broadcast` here.

**Comment by DavidVorick** [comment]
So, basically if you call another module in a goroutine, you get a hiccup in the control flow, as far as things like Flush are concerned. Your options are either to let the control flow drop, or to not shut down until the call completes:

```
go g.Broadcast(x) // control flow dropped - you aren't certain whether g.tg.Add() was called
go func() {
    cs.tg.Add()
    g.Broadcast(x)
    cs.tg.Done()
} // cs can't Flush or Close until Broadcast returns, which it may not want to wait for.
```

I guess I can see the argument that the second option is good enough, but it means that quick-clean-shutdown requires being able to close modules out of order, something we don't currently support. (all exported functions would need to return errors)

**Comment by DavidVorick** [comment]
I have another reason that `Broadcast` should be non-blocking. It's broadcasting a message to a flood network, and it's poor design to block until a message has been sent out. Furthermore, as mentioned above, `Broadcast` returning successfully does not actually indicate that the message made it out to the network.

The `Broadcast` function should really be more like a `QueueBroadcast` function, and I stand by my previous assertion that it really should not be blocking until the networking has completed.

**Comment by lukechampine** [comment]
Closing this because `Broadcast` hasn't caused us any problems in a while now. Perhaps we can revisit if/when there's another Gateway overhaul.
