### ISSUE TITLE
Theoretical Controller

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#1368]
There has been some discussion between @lukechampine and myself about having a central controller which manages as much of the concurrency and asynchrony of `siad` as possible. This idea has been around for a while, but in the interest of learning from the idea I want to flesh out a design some more in this issue.

We are not planning on switching Sia to a controller as it would be an overhaul of massive parts of the codebase. But having a better understanding of what a controller would look like might bring out some patterns that we can apply to the existing Sia codebase without requiring sweeping changes, or it might bring up ideas that can be applied to the current, independent-objects design.

A major shortcoming right now is concurrency control. The current project does a ton of things asynchronously, and for testing purposes especially it's very difficult to know when an action has completed.

For example, if we have three consensus sets connected to eachother, and one mines a block, how do we know that the second consensus set has received the block? How do we know that the host of the consensus set has received a block? How do we know that the host has submitted a storage proof after receiving that block? Or maybe we are being too fine-grained, and don't need to see that many details. Maybe we just set a bunch of nodes up, have them all run for a while doing uploading and such, then after a while we check the balances on each to make sure that everything eventually happened? But something that vague is probably still very hard to test.

It would be good to have a fine-tuned understanding of every asynchronous action that's happening.

I have a second example, but have run out of time, I'll post it next. It relates to consensus set subscription, specifically what to do if a module at boot does not have the most recent block.

**Comment by DavidVorick** [comment]
Ok, so the second example involves data flow in the project. First a block comes in, presumably something is waiting for input, gets a block, then passes the block to the controller. The controller passes the block to the consensus set, and the consensus set validates the block, updating itself. Then the controller sends the block to all the modules.

How does the controller manage ordering? What happens if you get concurrent calls/queries that will change depending on block propagation (such as an incoming transaction that is valid without the block but invalid given the block)? What happens if siad closes before the block is passed to all modules?

Right now, a pretty significant limitation is that each module has a separate database. Each module processes blocks separately, and we currently give every module all the information that it may need, instead of just the information it needs.

Having a global database of all known hashes to data for blocks and transactions could be valuable. May some other centralized data models as well. But then you get coupling where changes affect all modules.

**Comment by lukechampine** [comment]
Let me try to sketch what I envision this construct looking like:
```go
func (c *Controller) hostListen() {
	for {
		conn, err := c.hostListener.Accept()
		if err != nil {
			break
		}
		go c.host.HandleRPC(conn)
	}
}

func (c *Controller) renterRepairLoop() {
	for {
		select {
		case <-time.After(5 * time.Second):
			c.renter.Repair()
		case <-c.closeChan:
			return
		}
	}
}

func (c *Controller) blockHandler() {
	select {
	case block := <-c.blockCh:
		cc := c.consensus.ComputeConsensusChange(block)
		c.host.ProcessConsensusChange(cc)
		c.renter.ProcessConsensusChange(cc)
	case <-c.closeChan:
		return
	}
}

func (c *Controller) signalHandler() {
	sigChan := make(chan os.Signal)
	signal.Notify(sigChan, os.Interrupt, os.Kill)
	select {
	case <-sigChan:
		close(c.closeChan)
	case <-c.closeChan:
		return
	}
}

func (c *Controller) Run() {
	go c.hostListen()
	go c.renterRepairLoop()
	go c.consensusChangeHandler()
	go c.signalHandler()
	<-c.closeChan
}
```
The basic idea here is that we are hoisting background goroutines (such as listeners and interval-based actions) out of the modules and into an orchestrating layer called the Controller. In addition, modules no longer register callbacks with other modules, such as with `ConsensusSetSubscribe`. Instead, the Controller is responsible for wiring the modules together. As a result, each module becomes completely deterministic; their state will not change unless you call one of their methods. They become less like actors and more like libraries.

This centralization makes it easier to trace the flow of events through the system. For example, we can quickly see how incoming blocks are received via a gateway RPC (omitted from the above code), processed by the consensus set, and finally propagated to each module. In the current codebase, this is a much trickier ordeal. We begin by examining the gateway: there is nothing about blocks, but there is a `RegisterRPC` method, so we hunt around in the consensus module and find that it registers `threadedReceiveBlocks`. `threadedReceiveBlocks` calls `AcceptBlock` on the received blocks, computes a consensus change, and calls the `ProcessConsensusChange` on each "subscriber." So the last step is to locate where `ConsensusSetSubscribe` is called so that we can figure out which modules will actually receive the block.

As you stated, the problem we're currently facing is: "how can I block until a given event has been fully processed?" For example, after making an API call that should result in contract formation, we would like to be able to confirm that the host actually ran the `FormContract` RPC. Currently, the only way to do this is to repeatedly check the host's metrics until the number of contracts increases. This is because the host runs its own network listener and gives no indication that it has received an incoming connection. With a Controller, you could do something like this:
```go
type hostMock struct {
	modules.Host
	ch chan struct{}
}

func (hm hostMock) HandleRPC(conn net.Conn) {
	hm.Host.HandleRPC(conn)
	ch <- struct{}{}
}
```
This sort of mock is not possible with the current architecture because the necessary methods are hidden inside the modules. Their event handling is simply inaccessible.

---

From the other issue:
>the picture I'm getting is of a large, prone-to-spaghettify codeset that handles all input into the Sia daemon. What happens when you want to add a new RPC? A new time-related operation? A new API call that the user can interact with?

Indeed, the tradeoff with this approach is that you get one big blob of complexity instead of half a dozen smaller blobs. Adding a new RPC or API call might be more of a hassle than it is now -- but I think the hassle would come from the Controller forcing you to think about how the new call interacts with the system as a whole. If that proved true in practice, I think we can agree that it would be a positive, in the same way that Go's in-your-face error model is a positive because it forces you to think about failure. Adding a new API route or RPC call isn't something that should be done lightly.

>How does the controller manage ordering? What happens if you get concurrent calls/queries that will change depending on block propagation (such as an incoming transaction that is valid without the block but invalid given the block)?

I'm not sure I follow. How does our current code handle that example?

>What happens if siad closes before the block is passed to all modules?

Currently, each module keeps track of its most recent consensus change, and will call `ConsensusSetSubscribe` using that change in order to resubscribe at the correct height. In a Controller-based model, this would have to be handled a bit differently. One approach would be for the modules to report their current CCID via an exported method. The controller would call this method at startup to determine which blocks to pass to the module. Alternatively, the Controller could keep track of the CCID of each module, updating it as soon as the call to `ProcessConsensusChange` completes.
In the same vein, I'm not sure how rescanning would best be handled. Worst case, modules would need to export a `Rescan` method.

In summary, here's a list of the pros, cons, and questions that I can think of:

:heavy_plus_sign: Events are first-class; easy to trace the flow of an event through the system
:heavy_plus_sign: Inter-module events can be managed in one place (no more subscription or registration)
:heavy_plus_sign: Less duplication of objects like blocks, transactions, current block height, etc.
:heavy_plus_sign: Easier to test modules in isolation
:heavy_plus_sign: Modules have fewer dependencies (e.g. consensus no longer needs gateway)

:heavy_minus_sign: Code relating to each module is split between the module itself and the Controller
:heavy_minus_sign: Controller has poor separation of concerns; might be difficult to maintain
:heavy_minus_sign: Modules might need to export ugly methods for the Controller's sake (i.e. coupling)

:grey_question: How does the Controller interact with the API?
:grey_question: How are gateway RPCs handled?
:grey_question: Does this affect logging? Do modules still need their own loggers if all errors can now be propagated to the Controller?

Addendum: [a nice article on the perils of threads](https://glyph.twistedmatrix.com/2014/02/unyielding.html). Key quote:
>When you’re looking at a routine that manipulates some state, in a single-tasking, nonconcurrent system, you only have to imagine the state at the beginning of the routine, and the state at the end of the routine. To imagine the different states, you need only to read the routine and imagine executing its instructions in order from top to bottom. By contrast, in a system with arbitrary concurrent execution – one where multiple threads might concurrently execute this routine with the same state – you have to read the method in every possible order.

**Comment by DavidVorick** [comment]
You end up with a giant controller. I don't think that's a good design pattern, given the size of our codebase and the sheer number of things that are happening. 

I for example don't think I like the idea of a controller looking at a module's progress and then deciding what blocks to give it. That seems very limiting. What happens if a rescan is needed? For example, in the wallet, the addition of a new seed means a rescan should be performed. That means that the controller is going to need to give the wallet all of the blocks again, but if the controller is the one making those decisions, how does the wallet writer signal to the controller that it needs all the blocks? Make an exported method and hope the controller uses it?

We want the app to be highly concurrent. That makes reasoning about certain things a lot more difficult, but it's a clean way get multiple independent processes running at the same time.

Best I can tell, the controller is just a way to expose a bunch of knobs in `siad` that we can easily interact with from outside the package. But this really isn't that much different from having a ton of exported methods.

I'm pretty sure that we want modules to have their own logs. Some of the modules, especially while under construction, have a massive amount of logging information. Dozens or hundreds of megabytes. Others only have a few hundred lines of logs. If a user is going through and cleaning out the large files, it probably makes sense for us if they see a 1GB gateway.log and delete it, leaving behind the 35k consensus.log instead of seeing a 1.1GB global log and deleting that, tossing less-spammy and more critical messages that have been posted to the more stable consensus log. (At this point we're ready to reduce the gatway logging, but let's pretend that we're 3 months in the past where this example would be more relevant. Today I think it's the host and contractor that are going to have the spammy logs).

> By contrast, in a system with arbitrary concurrent execution – one where multiple threads might concurrently execute this routine with the same state – you have to read the method in every possible order.

That definitely depends on the design. If you use good design, the actors don't interact frequently and their interactions are guarded - either the ordering of the interaction is explicit or it is demonstrably irrelevant.

We are constantly making changes to the control flow of our modules. For example, the wallet is going to be getting a new type of rescan. The hostdb's scanning process is likely to change. At some point, we'll want to add host announcements to our flood network (via the Gateway) instead of using the blockchain to manage that.

And, how does the controller play into interactions between the renter and its submodules? For example, the hostdb needs a lot of feedback from the contractor about how file uploads happened. The contractor can feed the data directly to the hostdb, or the contractor can feed the data to a controller which feeds the data to the hostdb. To me the controller step seems unnecessary and overly-complex. You end up combining a large number of different functions into one object, which is going to make programming around it very difficult.

What if we had a controller for each module? For example, the host has a stateful piece, and then the host has a controller piece. The controller for the host manages all continuous threads, all RPCs, and all user interactions (exported methods), but is still limited to just the host. Then we can export the pieces of the controller as we need to for testing, but using an interface which is only used to create the ServerTesters (like the TestMiner), and not an interface that is used for production code.

It seems to me like the core concern here is the ability to control what is happening. We should find ways to achieve that without merging orthogonal functions. We split up the modules for a reason, and I think it's been very beneficial to development. Imagine that I'm working on the hostdb, you are working on the renter, and Jordan is working on the gateway, and we're all modifying the control flows of our modules. Are we all also going to be competing for dev time on the controller object?

> Adding a new RPC or API call might be more of a hassle than it is now -- but I think the hassle would come from the Controller forcing you to think about how the new call interacts with the system as a whole. If that proved true in practice, I think we can agree that it would be a positive, in the same way that Go's in-your-face error model is a positive because it forces you to think about failure. Adding a new API route or RPC call isn't something that should be done lightly.

It depends on what we are talking about. We want flexibility, and part of the reason that we split up the modules is that we shouldn't have to think about the system as a whole when we're making changes to something like the wallet. The system is too large and too complex for a single developer to reasonably be able to consider the system as a whole. That's why we develop it in smaller pieces, and have clear lines for how the pieces interact with eachother. When you are modifying the renter and using the wallet, you don't have to think about the implications of the host and the miner making use of the wallet at the same time - the wallet is designed to be thread safe, such that it doesn't matter what the host and miner are doing.

Sia is going to continue getting more and more complex as a whole. The only way that we are going to be able to stay on top of it is if we work hard to make sure that each piece has a limited number of interactions, and that when working on that piece alone it's total potential interactions are small enough for a single developer to easily reason about them.

I don't think a global controller is conducive to that. But I do see the potential advantages of having local controllers. In a way, `Flush()` is a blunt and primitive controller - it allows you to freeze/finish all actions on a module, in a way that poorly specifies what counts as an action. What you want seems to be a way to freeze/finish actions with more precision, and with better specification of what exactly is being frozen/completed. I think those things are good, but only if we can implement them in a way that keeps a firm lid on the total amount of complexity of any given part of the codebase.

> Inter-module events can be managed in one place (no more subscription or registration)

The module is still technically subscribing to the controller. It's a little different because the controller is the one creating the module, but the fact remains that there is some process responsible for pushing updates from the blockchain and from the transaction pool to the module. Complexity-wise, I think that's the same amount of complexity as the current subscription model.

> Events are first-class; easy to trace the flow of an event through the system

But wouldn't the ability to trace the flow of an event require having a good understanding of the controller, something which is likely going to be the most complex part of the whole project? I would argue that in a well designed project, you shouldn't have to trace an event through the system. To grab your example:

>  We begin by examining the gateway: there is nothing about blocks, but there is a RegisterRPC method, so we hunt around in the consensus module and find that it registers threadedReceiveBlocks. threadedReceiveBlocks calls AcceptBlock on the received blocks, computes a consensus change, and calls the ProcessConsensusChange on each "subscriber." So the last step is to locate where ConsensusSetSubscribe is called so that we can figure out which modules will actually receive the block.

Consensus is currently fully managed by the consensus set. The process of synchronizing to the network, doing IBD, etc, might be a process which belongs in a separate module, but more or less if you are wondering about where a block comes from, you should be starting in the consensus set. I don't know how difficult it would be to find the `threadedReceiveBlocks` function, or how hard it would be to realize that `synchronize.go` is a good starting place. But if you are in the consensus set, your primary concerns should be where blocks come from and where they go to, not what happens afterwards.

If you are in the renter, you shouldn't have to worry about any of that, it's abstracted away. You've got this `ProcessConsensusChange` function that tells you everything you need to know about consensus, and then there should be no more concerns for you about the flow of blocks in the rest of the system. Being able to trace an event through the whole system is not a design goal.

Are there specific instances where you felt, for debugging reasons or otherwise, that you had to trace an event through the whole system?

**Comment by lukechampine** [comment]
I guess I'm still refining my concept of where the Controller's responsibilities begin and end. Having the Controller manage all module interactions is definitely overkill. Clear event flow is the most important goal.

>I for example don't think I like the idea of a controller looking at a module's progress and then deciding what blocks to give it. That seems very limiting. What happens if a rescan is needed? For example, in the wallet, the addition of a new seed means a rescan should be performed. That means that the controller is going to need to give the wallet all of the blocks again, but if the controller is the one making those decisions, how does the wallet writer signal to the controller that it needs all the blocks? Make an exported method and hope the controller uses it?

The Controller should be responsible for forwarding incoming blocks to each module (since an incoming block is an event), but not for ferrying blocks between modules. In the situation you describe, I'd be ok with something like this:
```go
func (w *Wallet) AddSeed(seed modules.Seed, cs modules.ConsensusSet) error {
    w.seeds = append(w.seeds, seed)
    w.reset()
    for i := 0; i < w.currentHeight; i++ {
        w.processBlock(cs.BlockAtHeight(i))
    }
}
```
The wallet is now fully in control of how it accomplishes the rescan. The Controller doesn't even need to know that a rescan occurred.

>Best I can tell, the controller is just a way to expose a bunch of knobs in siad that we can easily interact with from outside the package. But this really isn't that much different from having a ton of exported methods.

The knobs aren't exported. The idea is that most of our integration testing would be done in the same package as the Controller, so we'd have direct access to the knobs.

>I'm pretty sure that we want modules to have their own logs

Agreed, though I don't know much about how logging is usually done in big apps like this. Some apps log everything to stderr (or a separate daemon, e.g. `syslog`) with a tag indicating the subsystem responsible.

>How does the controller play into interactions between the renter and its submodules? For example, the hostdb needs a lot of feedback from the contractor about how file uploads happened. The contractor can feed the data directly to the hostdb, or the contractor can feed the data to a controller which feeds the data to the hostdb. To me the controller step seems unnecessary and overly-complex.

As in the wallet example, the renter can call hostdb methods directly.

>What if we had a controller for each module? For example, the host has a stateful piece, and then the host has a controller piece. The controller for the host manages all continuous threads, all RPCs, and all user interactions (exported methods), but is still limited to just the host.

This is pretty funny because you're basically describing our UI architecture. We have a set of "dumb" objects called components, which simply render whatever data they are given. On top of that, we have a set of smart objects called containers, which are responsible for managing state and passing it to the components.
I'm open to exploring this more, but I'm not sure if it would achieve the sort of explicitness that I'm looking for. Wouldn't you just wind up with the wallet controller subscribing to the consensus controller, and the consensus controller registering RPCs with the gateway controller?

>Imagine that I'm working on the hostdb, you are working on the renter, and Jordan is working on the gateway, and we're all modifying the control flows of our modules. Are we all also going to be competing for dev time on the controller object?

Generally no, because most of the module-specific logic will be contained within the module. If two people need to modify the propagation of the same event, then there will be a conflict -- but there would be a conflict anyway. Better to step on each other's toes than silently introduce a bug.

>The module is still technically subscribing to the controller. It's a little different because the controller is the one creating the module, but the fact remains that there is some process responsible for pushing updates from the blockchain and from the transaction pool to the module. Complexity-wise, I think that's the same amount of complexity as the current subscription model.

It's important to distinguish essential complexity from accidental complexity. Both approaches have the same amount of essential complexity, but their accidental complexity may vary. Subscription means the module has to take a `ConsensusSet` as an argument and subscribe to it. A Controller moves that responsibility out of the module.
That said, I'm no longer sure that the Controller needs to manage subscription. As long as it has some means of determining that a block has been fully processed, that's sufficient for the purposes of event flow. Registering modules as subscribers isn't much different from passing them as arguments, as in the wallet example above:
```go
subscribers := []modules.ConsensusSetSubscriber{host, renter, wallet}
cs.AcceptBlock(block, subscribers)
```
This is nice because you can infer the effect of `AcceptBlock` from the callsite. In the subscriber model, the propagation of block -> module is implicit in the `AcceptBlock` call; you need to know the internal state of the `ConsensusSet` to figure out who will receive the block.

>Being able to trace an event through the whole system is not a design goal. Are there specific instances where you felt, for debugging reasons or otherwise, that you had to trace an event through the whole system?

For me, debugging is mostly a process of figuring out what state the program was in and why. That typically means traversing the callstack. Admittedly, I rarely need to traverse all the way up to the source of the event. Also, I don't write many integration tests in the `api` package, which I imagine is where this level of control would be most useful. Since you have more experience writing those tests, you're in a better position to judge the merits of any given approach.

Modularity is generally a good thing, but at some point you need to glue the modules together. For example, we could make each module an `http.Handler`; then each module could be responsible for its own API routes. But this would be bad design because the individual handlers only make sense when combined into a complete API. Collecting all the routes in one place is beneficial because it allows us to reason about the API as a whole. Likewise, I think the Controller would allow us to reason about Sia as a whole.
