### ISSUE TITLE
"null" empty arrays in API JSON responses

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#1406]
`nil` slices are marshaled to JSON as `null`. In some cases this can be easily fixed as in #1250. However in cases where the empty arrays are nested in deep within the returned object the fix is not as easy. For an example see the `/wallet/transactions` endpoint.

Is it desirable to return an empty array instead of `null`? I think it is reasonable to expect the API to be consistent. Googling around it seems like some APIs do return `null` for empty arrays. Another solution which seems more common is to omit the field if the array is empty. This is supported by [Google's JSON Style Guide](https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Empty/Null_Property_Values#Empty/Null_Property_Values).

Furthermore would changing this behavior break our API stability promise?

**Comment by DavidVorick** [comment]
Was this addressed?

**Comment by lukechampine** [comment]
I believe our API is still inconsistent on this. Some fields return an empty array, some return `null`. I think empty arrays are preferable because you can iterate over them, whereas iterating over `null` (or `undefined`) causes an error. However, it may be standard in the JS ecosystem to expect that APIs won't return an empty array. One benefit of this is smaller JSON values: our `types.Transaction` type would be a lot smaller if we used the `// json:"omitempty"` field tag, since its slices are frequently empty. But it's definitely too late to make such a breaking change.

**Comment by VoidingWarranties** [comment]
I guess the best we can do is keep this in mind for API v2.
