### ISSUE TITLE
logfiles are not in local timezone nor does it state what timezone it is

### ISSUE THREAD

**Issue by vevarm** [NebulousLabs/Sia#1486]
On ubuntu in stockholm. I am guessing log times are in UTC, but that is very confusing, especially when it does not state so in logs. 

Minor thing, but easy to fix, right?  Rather have it in local time and stated it is in local time. 

overall I am very impressed what you have built here, tried storj first, it does not compare. 

//Cheers

**Comment by DavidVorick** [comment]
Thanks for the encouraging words. Log times are in UTC because Sia is a global network. In the event that something strange happens on many machines at once, we want to be able to match the logs. This is easiest if the timestamps are all in the same timezone. Machines may still be off due to inaccurate clocks, but it still makes our lives easier to be able to say 'oh yeah this happened during the DDOS attack' or whatever.
