### ISSUE TITLE
Failure to reach consensus

### ISSUE THREAD

**Issue by Firescar96** [NebulousLabs/Sia#1506]
I upgraded to version 1.0.3 and something broke. I am a file hoster, but for the past few days I haven't been able to host.
Siad starts normally.
```Loading... 
(0/7) Loading siad... 
(1/7) Loading gateway... 
(2/7) Loading consensus... 
(3/7) Loading transaction pool... 
(4/7) Loading wallet... 
(5/7) Loading miner... 
(6/7) Loading host... 
(7/7) Loading renter... 
Finished loading in 0.275266687 seconds
```

But then I try to unlock my wallet. Siac hangs (I've left it running for a few hours) at the unlocking wallet phase. siad is giving this output
```
Rescanning consensus set... 
Scanned to height 0...Rescanning consensus set... 
Scanned to height 0...Rescanning consensus set... 
Scanned to height 0... 
Scanned to height 0... 
```

`siac consensus` also hangs.

**Comment by DavidVorick** [comment]
Normally when this happens it's because you aren't caught up to the most recent height. The wallet and the blocks being downloaded fight for locks of the consensus database, and sometimes this can slow things down substantially.

Can you check what your height is before you unlock the wallet? If it is not at least 80,000, you will probably have better luck waiting until you are synced, and then unlocking the wallet.

**Comment by DavidVorick** [comment]
closing until further information provided
