### ISSUE TITLE
[enhencement] progress on siac renter download

### ISSUE THREAD

**Issue by vevarm** [NebulousLabs/Sia#1546]
Would be useful and nice with some progress output for the siac download command.

**Comment by DavidVorick** [comment]
@vevarm if you don't mind me asking, what workflow has you using siac? Why is it important to you vs. the GUI?

And, I only ask because I'm trying to get a sense of how many users we have on each. Right now we don't actually put much development time into siac (not that it needs it, a cli is inherently a lot simpler to write + maintain than a graphical client), but if we have a bunch of users who regularly use siac, it definitely makes sense for us to dedicate more time towards making it powerful + easy to use.

**Comment by vevarm** [comment]
I have a serveral backup strategies one is to tar all the latests photos and videos into chunks of 20 files and upload them to s3 glacier class and sia. This is done with a simple script using siac. Genereally I think siac does its job the usage info for the commands is sufficient to get me going.

**Comment by vevarm** [comment]
If I get to wish for more out of siac it would be list commands for renter contracts that is a real black hole. I am a persion who like to dig into stuff and want to know the innerworkings, its a bit frustrating not having a clue about these contracts, what have I really signed? Why is sia uploading to that expensive contract? Can I cancel that expensive contract?

**Comment by vevarm** [comment]
I dont use the GUI, siac runs on a headless. I did however use the GUI when first trying out sia.

**Comment by DavidVorick** [comment]
Cool, thanks for the feedback. Really cool to know that you are using Sia as a part of your data backup strategy, that is exciting to me.

We agree that the contracts are a black hole. If we allowed more technical users to select their own contracts, instead of doing everything automatically, they would likely be able to pick out much better hosts. (on the other hand, less technical users are likely to pick out much worse hosts).

We definitely have plans to give more insights to users about the contracts, and to give them more control over which contracts are being formed and utilized. I am not sure what the timeline for that is, but you are not the only person who has asked for this.
