### ISSUE TITLE
siad not shutting down gracefully when blockchain not fully synced

### ISSUE THREAD

**Issue by gowithplanb** [NebulousLabs/Sia#1614]
The `siad` daemon will not stop gracefully (when pressing Ctrl+C in the terminal) if the blockchain hasn't finished synchronizing. If the blockchain is up-to-date, the daemon stops very fast.

This is only a problem when starting/stopping the daemon while testing and the blockchain hasn't been fully downloaded yet.

**Comment by lukechampine** [comment]
Seems like this is because the peer connections are not closed as soon as the shutdown signal is received. The minimally invasive change would be to add some code to `ConsensusSet.managedReceiveBlocks` that gracefully (or perhaps forcefully) closes the connection when the signal is received. More heavy-handed would be to add code to the gateway that closes _all_ peer connections during shutdown. I'm in favor of the former because there might be special cases where we don't want a peer connection to be forcefully dropped, but I don't think we currently do that anywhere.
