### ISSUE TITLE
Abut Sia

### ISSUE THREAD

**Issue by 2smpl2** [NebulousLabs/Sia#1741]
Hi all
I've been hosting on Siacoin for a few weeks. The expected SC slowly group to around 120 and now seems to have stopped; the active contract seems to be steadily increasing up to 54 and earned is still 0. When should I expect to earn some of these coins and what else can I expect?
What I find strange is that even thought I have 40gb allocated, the Storage Folder grew to about 116mb and then stopped.
Cheers

**Comment by DavidVorick** [comment]
My guess would be that your host has a low score. Also, renters tend to avoid hosts with less than a few hundred GBs of storage, because they do not want to have a host that is about to fill up and become unavailable for uploading.

You can see more about your score with `siac hostdb -v` in the 'terminal' of the UI, or you can check out siahub.com, which has some support for exploring host scores.
