### ISSUE TITLE
smux code review

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#1742]
We've been meaning to switch away from muxado for a while, and one of the options that has come up is smux. I went ahead and read the whole codebase, and here are my thoughts (in no particular order):

1. Default KeepAliveInterval is only 10 seconds, and the KeepAliveTimeout is only 30 seconds. These are too fast, and probably won't do well when talking to nodes across the Great Firewall of China. However, they are also runtime-configurable. We can't use the defaults, but we don't need to modify the library to suit our needs.

2. There's a function `VerifyConfig`. At the very least, this means that the author is thinking about correctness and input validation, which is a good sign.

3. The whole whole thing is less than 1000 lines of code spread across only 4 files. This should make review easy, and if we ever run into problems, it should make discovering and repairing bugs pretty easy.

4. Author seems to be writing in idomatic go, and not doing too many clever things. This also suggests that it's a high quality library.

5. Each connection runs 3 goroutines:

- `session.recvLoop`
- `session.sendLoop`
- `session.keepalive`

That's unfortunately pretty heavy. We can work with it for now, but at some point we're probably going to want to clean up our goroutine footprint to reduce scheduling pressure. It seems to be nontrivial for us. Especially because it's common for hosts to have 40+ peers, we're talking a 100 goroutine overhead. Lots of threads also makes life more annoying when debugging.

6. The recvLoop allocates a []byte of side 64kib. The sendLoop also allocates a []byte of size 64kib. So we're talking a total of 128kb + 3 goroutines of automatica overhead per session. 100 peers is going to consume a minimum of 15 mib of ram, plus whatever overhead accompanies the GC pressure and defragmentation (defragmentation probably not too bad actually, b/c the large allocations are big slices, and they don't get GC'd ever as far as I can tell).

7. The goroutines perform clean + quick shutdown it seems. Resource management at least appears to be very clean, even if it is heavy.

Overall, this is some of the nicer go code I've ever read. Could use some more comments, but its small size makes the sparseness of comments not too worrisome, it's easy enough to read all related functions and types and get a feel for what's supposed to be happening.

Best I can tell, author was very careful regarding things like input validation, buffer overflows, bounded memory consumption. The protocol is versioned, so if we need to make a departure, we can do it at the smux level instead of needing to add more switches inside of the gateway code.

I know we had tossed around the idea of writing our own, but my smux review was very encouraging. At worse, I think we would start with the smux code and the adapt it to fulfill whatever needs it doesn't already meet. But, it seems like it's already what we need.

**Comment by lukechampine** [comment]
Thanks for taking the time to review this. I'm glad to see it come out so positively on the whole.

For comparison, I looked into muxado's equivalents for some of the values. muxado spawns one goroutine for reading, and three (!) for handling heartbeats. Like smux, it allocates 64KiB buffer by default, though I believe this is configurable. Finally, it defines:
```go
const (
        defaultHeartbeatInterval  = 3 * time.Second
        defaultHeartbeatTolerance = 10 * time.Second
)
```
which I imagine are analogs of `KeepAliveInterval` and `KeepAliveTimeout` -- about 1/3rd shorter. This could explain some desynchronization.

btw, seems like goroutines are unavoidable when doing network polling because Go doesn't allow you to `select` on a file descriptor the way `epoll` does. But honestly, goroutines don't concern me too much because they're cheap and the number of peers is small (128 max). 15MB is totally acceptable. The big stack traces are a larger annoyance than the memory as far as I'm concerned :P
