### ISSUE TITLE
Apply logarithm to score in hostdb output

### ISSUE THREAD

**Issue by starius** [NebulousLabs/Sia#1746]
It is hard for humans to operate with numbers which are in scale from 1e-16 to 1e+08.

**Comment by DavidVorick** [comment]
I don't want to do a logarithm because users will get confused about their score. They might see that they are at score '75', and that the top 50 hosts are at score '85', and think that they are pretty close. But in a logarithm, 75 and 85 are very, very far apart.

Instead we can probably replace anything below 1 with '0' or '<1', and we can probably replace anything above 100k with '100k+'

The majority of useful hosts will fall within the range 1 to 100k.
