### ISSUE TITLE
[improvement] fee calculated based on hard-coded transaction size estimate

### ISSUE THREAD

**Issue by RNabel** [NebulousLabs/Sia#1787]
When a host is announced, the fee for the transaction is based on a hard-coded estimate of the size of the transaction. Host announcements are therefore vulnerable to changes in the code used to sign transactions.

See source: https://github.com/NebulousLabs/Sia/blob/master/modules/host/announce.go#L48

Maybe the interface of the txn builder could be extended to automatically calculate the fees required for a transaction.

**Comment by lukechampine** [comment]
There are a few places in the code where we have to estimate the transaction fee for the same reason. Extending the txnbuilder seems reasonable to me. It's tricky because in order to pay for the txn fee, you need to call `FundSiacoins`, which adds an input/output to the txn and therefore changes the fee. So I'm not sure what to name the method or where in the process it should be called. I'm pretty sure it would be a bad idea to do something like:
```go
tb.FundSiacoins(txncost)
tb.FundFee()
```
because this would require the txnbuilder to compute two "change outputs" instead of just one. So maybe `tb.FundSiacoinsAndFee`? Hmm.

**Comment by lukechampine** [comment]
duplicate of #1479
