### ISSUE TITLE
Move Folder

### ISSUE THREAD

**Issue by smccloud** [NebulousLabs/Sia#1811]
I currently have my host setup to provide space on my main RAID array in my home server, I am planning on moving it to an external RAID array in the future.  I am worried about adding a new folder and removing the old one causing me to lose some of my collateral.  A folder move command to perform this action would be helpful for use cases like mine.

**Comment by lukechampine** [comment]
@DavidVorick is this possible by adding the new folder, then removing the old folder?

**Comment by tbenz9** [comment]
Recommendation to devs: "Feature Request"

**Comment by DavidVorick** [comment]
Yes, currently you can move your storage to a new drive by creating the new folder, and then removing the old folder.

This is the recommended way of doing it as well, because it'll happen under the host's ACID guarantees. If you are just doing a normal copy and you lose power halfway through, your files may be left in an unrecoverable state.
