### ISSUE TITLE
using master seed to unlock wallet

### ISSUE THREAD

**Issue by Gil80** [NebulousLabs/Sia#1886]
Hi.
This is a huge security risk.
Each time a user needs to unlock their sia wallet using sia-ui, they risk exposing the master seed to 3rd party. The master seed is very long and no one type it in. It's usually being copied and pasted to unlock the wallet, therefore having it copied to the clipboard is a huge security risk!

Please allow for the usage of passphrase to unlock a wallet.

**Comment by lukechampine** [comment]
You can already specify a custom passphrase. Check the appropriate box when creating a new wallet.

wrt the clipboard: This is not a valid concern; otherwise no one would recommend using password managers like KeePass, LastPass, 1Password, etc. Any password manager worth its salt will clear the clipboard after a timeout. The security benefit of a long password far outweighs the danger of it briefly living in your clipboard. If you are assuming that the computer may have malware, well, there's really nothing you can do to prevent your password from being compromised in that case, since the malware could be a keylogger. Or it could replace the Sia binary with a malicious binary. Or it could MITM the API requests made to the Sia daemon. etc. etc.
