### ISSUE TITLE
Loading Can Take A While After Loading A New Version

### ISSUE THREAD

**Issue by TJ700** [NebulousLabs/Sia#1908]
I installed my wallet last night and it worked and synchronized fine. Ever since restarting my computer I cannot get past this screen. I have reinstalled and tried multiple restarts of the program. I have waited hours, but still nothing, This seems to be a bug of some sort.

**Comment by joecoltech** [comment]
I have this issue as well. It won't load.

**Comment by TJ700** [comment]
I deleted the SIA folder from my roaming app data. This allowed me to reinstall properly. Interestingly, this appears to be the way to customize your password to be different from the seed.

However there were two problems. First, the wallet kept giving me different addresses for sending my coin to. Why would the same wallet have multiple addresses? This seems bugged unless it's some security feature or the like I don't understand.

Also, once I closed the wallet and restarted it the wallet wouldn't load and its a rinse and repeat of the whole thing.

My guess is it's a genuine bug that will be fixed with a patch.

**Comment by lukechampine** [comment]
>Why would the same wallet have multiple addresses?

Using the same address for all your transactions is a privacy issue. It makes it trivial for someone to track all your actions on the network. Admittedly, generating a different address each time is confusing for new users. There is some discussion around how we can improve this experience.

**Comment by phil9** [comment]
I have the same problem since yesterday night. Kept running my laptop for the whole night still same. This is so frustrating with sia no proper support or update. I have been synchronizing since the past 1 week and after reaching 73.6 percent it suddenly stopped synching last night. Who will continue to be part of sia with such bugs and issues which i see everyone complaining of. I am not sure all the hard work and days of efforts it seems all gone. I am not a techie. Can someone help and resolve my issue.

**Comment by tvance929** [comment]
I synched all the way after 28hours... couldnt see coins so rebooted my system... now back to this "loading can take awhile" stuff for days and days.
