### ISSUE TITLE
A future without port forwarding?

### ISSUE THREAD

**Issue by Slapbox** [NebulousLabs/Sia#1955]
Is there any chance of port forwarding being replaced with another mechanism? Siacoin is very cool, and I bought some to rent out storage space, but after learning I need to forward a port, I can't be doing that so I'm just holding my coins and my empty HDD space.

**Comment by lukechampine** [comment]
You don't necessarily need to forward your ports, but you do need your host port to be open. Otherwise, when peers try to form contracts with you, they won't be able to get through. Same goes for any server you talk to on the Internet.

Note that you don't need to have open ports to connect to peers on the network and exchange blocks/transactions. In a peer-to-peer connection, only one computer needs to have an open port. After the connection has been established, it can be held open indefinitely. But if neither peer has an open port, they can never establish the initial connection. This is one reason why it's important to have many peers on the network with open ports. Without them, the network can't function.

**Comment by Slapbox** [comment]
It sounds like I need to open the port on my router, is this accurate?

Torrents and other coin clients don't require that, but it seems to be the case for Sia.

**Comment by lukechampine** [comment]
Torrents and other wallets *do* require it, in the same sense I described above: the average user doesn't need to have open ports, but if *nobody* has open ports, the network cannot function.

I believe there are ways to get two peers behind NAT to connect to each other, but it requires a trusted third party and more infrastructure than we want to implement at this time.

**Comment by S-anasol** [comment]
>Torrents and other coin clients don't require that, but it seems to be the case for Sia.

Torrents use servers to let your client know peers. At least to make it faster than via DHT.
Also torrent clients uses upnp to avoid port forwarding setup.
So torrents bit centralised.

**Comment by lukechampine** [comment]
Yep, Sia uses UPnP too. It's just an programmatic way to tell your router to forward your ports. It also happens to be one of the worst protocols ever designed. :P
