### ISSUE TITLE
Document the siad data directories

### ISSUE THREAD

**Issue by nitronick600** [NebulousLabs/Sia#1971]
It would be extremely helpful to app devs if the data directories siad uses had thorough documentation about their format and contents.  e.g. `renter/,` `consensus/,` etc...

Understanding what the directories are used for in the Sia ecosystem is vital to app developers and making an incorrect assumption about what they contain can set projects back weeks or even months.

**Comment by lukechampine** [comment]
Part of the reason for this is that we currently do not make any guarantees about the format of these files or their compatibility between versions (though we do make a "best effort" to preserve compatibility). The only thing we promise compatibility on is the API. In truth, we don't really want other developers to build software that depends on these files, since they are subject to break at any time. In addition, writing and maintaining documentation for these files is time-consuming and we don't have much time to spare.

For now, developers should treat the data directory as a "black box." Their only knowledge of it should be:
- `siad` should be pointed at this directory in order to reuse the existing blockchain (and other data)
- I should backup this directory if I want to preserve my blockchain, wallet, host data, etc.

If you are set on reading/writing the files in the data directory, the best documentation is the code.
