### ISSUE TITLE
Panic in fastrand

### ISSUE THREAD

**Issue by hut8** [NebulousLabs/Sia#1979]
Steps:

```
go get github.com/NebulousLabs/Sia/...
siad
```

Then I got:

```
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
panic: fastrand: argument to Intn is <= 0: -277250048

goroutine 75 [running]:
github.com/NebulousLabs/fastrand.Intn(0xef798000, 0x10c43a0c)
        /home/liam/go/src/github.com/NebulousLabs/fastrand/fastrand.go:148 +0xa4
github.com/NebulousLabs/Sia/modules/renter/hostdb.(*HostDB).threadedScan(0x10cdb1e0)
        /home/liam/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/scan.go:335 +0x528
created by github.com/NebulousLabs/Sia/modules/renter/hostdb.newHostDB
        /home/liam/go/src/github.com/NebulousLabs/Sia/modules/renter/hostdb/hostdb.go:180 +0x630
```

Running on Linux raspberrypi 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017 armv7l GNU/Linux

I guess this is technically a bug in your `fastrand` library, but clearly it affects this project quite a bit. If you'd like me to refile the issue there, let me know.

**Comment by lukechampine** [comment]
`fastrand` is functioning as expected. `(math/rand).Intn` has the same behavior. The problem is that we are calling it like so:
```go
sleepRange := int(maxScanSleep - minScanSleep)
sleepTime = minScanSleep + time.Duration(fastrand.Intn(sleepRange))
```
RasPi is 32-bit, right? My guess is that casting the `time.Duration` to a 32-bit `int` results in overflow. Currently we don't support 32-bit, because our database (boltdb) is backed by an `mmap`'d file, and our blockchain is larger than 4GB.
