### ISSUE TITLE
`siac renter load` does not exist despite docs saying it does

### ISSUE THREAD

**Issue by mkeedlinger** [NebulousLabs/Sia#2000]
https://github.com/NebulousLabs/Sia/blob/861c9ecb7b88864daadd11cbfcd851464d6308d9/siac/README.md#renter-tasks

Just scroll down a bit and you'll find that it says there is a `siac renter load` is a command. This does not exist in the latest Sia client I just downloaded from [here](https://github.com/NebulousLabs/Sia/releases/tag/v1.2.2)

I really need this feature. It seems like it may have existed before.

**Comment by mkeedlinger** [comment]
For others who are looking for a way to download from another machine:

You have to take the entire `renter` folder and copy that to the other machine. There are plans to make a better way to do this later, however, this is the only way for now.

Just ping me if you have any questions.

**Comment by lukechampine** [comment]
I've updated your comment to link directly to the relevant section, and using a commit hash so that it won't change even if we update the docs later.

This functionality did indeed exist a while back. We removed it because we wanted to rethink how to best implement file sharing. It's definitely a priority for us, but there is much work to be done before it's ready for release.
