### ISSUE TITLE
siac renter upload to accept stdin

### ISSUE THREAD

**Issue by olcto** [NebulousLabs/Sia#2002]
A basic unix way of programs interacting with programs is with stdin and stdout using pipe (|). I have a use case where I want to send a backup of a ZFS snapshot to Sia cloud storage with compression and encryption. For example on a unix command line:

zfs send storage@20170625 | gzip | openssl enc -aes-256-cbc -a -salt | siac renter upload - storage_20170625.gz.ssl

This has many advantages:
- Local HDD space is saved by not having to save the ZFS snapshot to file
- Compression is leveraged using gzip
- The file is encrypted with openssl before it leaves the computer independent of Sia protocol

My current snapshot size after compression is 122.7 GB ... so a broken pipe would be a bummer if the upload failed for some reason, i.e. a timeout. As there would be no way to resume from where it failed.

Does Sia have this capability? Has anyone tried this before? BTW, I am a total Sia noob and have been reading a lot about it this past week and will be setting up a Sia host this week. I would like to start using the Sia network as a renter, but this would be my use case. Thanks!

**Comment by lukechampine** [comment]
Currently Sia does not support uploading from stdin because it seeks around a lot in the file, uploading different chunks in parallel instead of sequentially. It's certainly feasible for Sia to support sequential uploads, but in your case I wouldn't recommend it. Uploading 120 GB will take a while, and with no way to resume, you'd just have to hope that nothing interrupted the transfer. If hosts disconnect or unacceptably increase their prices or run out of space or the contract runs out of funds or your computer crashes, you're outta luck and have to restart from scratch.

btw, piping through `openssl` shouldn't be necessary, since Sia automatically encrypts everything you upload. (No harm in it if you want a little more security, though.)

**Comment by lukechampine** [comment]
I don't think we plan to support streaming uploads in the near future. The use-case is narrow and I don't see a way to make the operation "safe" (i.e. recoverable in the event of a failure)
