### ISSUE TITLE
Why is data encrypted after adding erasure codes not before?

### ISSUE THREAD

**Issue by starius** [NebulousLabs/Sia#2005]
From https://siawiki.tech/renter/renting#uploading_and_downloading

>  The uploading process is as follows. First, the file is striped into chunks of 40MB. Reed-Solomon erasure coding is then applied on each chunk, expanding them into 30 pieces of 4MB. Erasure coding is like an M-of-N multisig protocol, but for data: out of N total pieces, only M are needed to recover the full 40MB chunk. This ensures a high level of redundancy, much greater than traditional replication.
>
> **Each piece is then encrypted with the Twofish algorithm**. It was one of the five finalists of the Advanced Encryption Standard contest, but it was not selected for standardization. Nonetheless, this algorithm is considered very secure.
>
> Finally the pieces are sent to hosts to be stored.

Code: [managedScheduleChunkRepair](https://github.com/NebulousLabs/Sia/blob/95733d23efa4f5361e7570e9bf151336530c1baf/modules/renter/repair.go#L402-L426).

So it currently works as follows:
40MB plaintext -(RS)-> 120MB plaintext -(Twofish)-> 120MB ciphertext

I propose to do it this way:
40MB plaintext -(Twofish)-> 40MB ciphertext -(RS)-> 120MB ciphertext

That would decrease encryption overhead 3 times. Also, if a host fails and renter has to repair the pieces hosted on that host, currently this involves decryption and encryption. If erasure codes were added after encrypting, then repairing a piece would not involve crypto at all.

**Comment by lukechampine** [comment]
It was actually a very early decision to order it this way. The rationale is that each host gets data encrypted with a different key. In the attack scenario where hosts collude to reconstruct your file, using one key means that the hosts collectively need to brute-force one key instead of 20.

Additionally, performing the encryption on a per-host basis makes the protocol more flexible, since you could (e.g.) use a previously-agreed upon key for a particular host, or skip the encryption step altogether for a host that you trust.

Lastly, the overhead of encryption is fairly small compared to the benefits it provides. I believe the storage overhead is ~20 bytes per 4MB sector, and the encryption time should be a fraction of the transfer time. (Granted, this depends a lot on the algorithm used. In my tests, Twofish appears to be far slower than AES. We could improve here.)

**Comment by starius** [comment]
Another argument for the current implementation was mentioned on Slack: hosts could collaborate to deduplicate pieces to reduce storage costs which would threaten data availability and durability. Encryption prevents them from doing this because it makes data looking random to hosts.

**Comment by starius** [comment]
> In the attack scenario where hosts collude to reconstruct your file, using one key means that the hosts collectively need to brute-force one key instead of 20.

The same effect can be achieved with encrypting each piece of the file with a different key and then add erasure codes. I don't think we have to add such kind of protection on top of Twofish - if Twofish is broken we have a problem anyway.

> use a previously-agreed upon key for a particular host

Can you elaborate on this, please? (I don't understand this sentence.)

> skip the encryption step altogether for a host that you trust.

This seems very dangerous - even if it is your own hosts, the data would be written on its hard drive in plaintext form. Also, it would be transferred via network unencrypted!

> I believe the storage overhead is ~20 bytes per 4MB sector

The encryption key is [derived](https://github.com/NebulousLabs/Sia/blob/95733d23efa4f5361e7570e9bf151336530c1baf/modules/renter/repair.go#L424) from a per-file master key. Why is there a storage overhead at all?

> Lastly, the overhead of encryption is fairly small compared to the benefits it provides.

I meant CPU cycles overhead not storage or network usage overhead. Encryption is an expensive operation especially Twofish done in Go. (AES is faster even without AES-NI. With AES-NI it is really fast.)

I wrote [a small script](https://gist.github.com/50c49eff7b17a683e3b053905c9c7c12) to measure the overhead of encryption. The result on my machine is:

```
Encryption of 1GB with twofish takes 14.986946533s.
```

Time to send 1GB of data over 1Gbit link is 8 seconds. So the overhead of encryption is actually higher than the overhead of network in my case.

**Comment by starius** [comment]
I came up with another argument for the current order (add erasure codes, then encrypt): it prevents adversaries from inferring file sizes which can be used to match your files with well known files collections to predict which files you upload.

But we don't have to use encryption after adding erasure codes to mitigate this attack. We can concatenate files before splitting them into pieces (as torrent does). Then adversaries will know only sum of files sizes which they know anyway.

**Comment by lukechampine** [comment]
I think your first counter argument is the most important. It's a big problem if hosts can reconstruct the file, because that allows them to lie about how much redundancy they are providing.

You'd probably only eschew encryption if storing on a host on the same LAN.

I'm not happy about those encryption speeds. They will become increasingly important at scale. One solution would be to encrypt the next piece while uploading the current piece. That should eliminate much of the overhead, at the cost of more memory usage.

**Comment by starius** [comment]
> I think your first counter argument is the most important. It's a big problem if hosts can reconstruct the file, because that allows them to lie about how much redundancy they are providing.

This attack is expensive for hosts. In this attack a renter happens to choose at least 11 malicious hosts to upload pieces to. (10 hosts are needed to recover pieces and 1 extra host is needed so that they can save storage costs on it.)

Those malicious hosts have to find pieces they can combine which is not trivial. Using encryption to prevent this is hunting squirrel with a howitzer. I believe there are cheaper ways to do it. I'm bullshitting here but why not to apply a unique permutation to the parts of the piece? Only renter would know the order of parts.

**Comment by lukechampine** [comment]
Closing this. BTW, the reason Twofish is so slow is that the package isn't written in asm. We could either switch to a faster algo (AES or perhaps ChaCha20) or commission someone to write an optimized Twofish package. I'll make a separate issue for it.
