### ISSUE TITLE
File download with locked wallet

### ISSUE THREAD

**Issue by S-anasol** [NebulousLabs/Sia#2136]
Not sure this is expected behavior or not.
It works with locked wallet, at least via GUI.

But this is insecure i think.

**Comment by lukechampine** [comment]
There is no technical reason to require the wallet to be unlocked in order to download files. The money is already allocated in the file contact; you aren't spending any additional outputs when you download.

I can see why this confusing though. The user may view the wallet password as a lock on the whole Sia interface. This is not the case. For that purpose, you would want to set an API password. Perhaps we need to make this more clear to users somehow.
