### ISSUE TITLE
Bounty for Minio Integration: 300,000 SC

### ISSUE THREAD

**Issue by zachherbert** [NebulousLabs/Sia#2155]
![sia minio](https://user-images.githubusercontent.com/14018740/28382306-ac5de1b0-6c8b-11e7-963c-0f422ae5856c.png)
**Welcome to Sia Bounties!** Learn more about the program at our [blog](https://blog.sia.tech/announcing-sia-bounties-800daf90398b).

To start, we are offering a 300,000 siacoin integration bounty for [Minio](https://minio.io/), a popular project in the storage space. Based on today's exchange rate, that's worth about $2300. 

Why Minio? Minio is a leading distributed object storage server built for cloud applications and devops. It is best suited for storing unstructured data such as photos, videos, log files, backups and container/VM images. Minio is open source under the Apache 2.0 license, and is compatible with Amazon S3 cloud storage service.

Minio has over 4 million downloads and a very active development community.

A Sia+Minio integration means that users will be able to expand their Minio clouds with cheap, secure, redundant storage on the Sia network. Since all files on Sia are split apart, encrypted, and stored across dozens of worldwide nodes, Sia provides a natural way for users to back up their files on Minio without relying on centralized parties like Amazon.

If you are interested in building this integration, please review the below requirements and the [blog post](https://blog.sia.tech/announcing-sia-bounties-800daf90398b). All Sia-related discussion should take place here or on our [Slack](https://slackin.sia.tech), with nontechnical discussion at #bounties and technical discussion at #app-dev.

If you have questions for Minio, either technical or nontechnical, you can reach them on their [Slack](https://slack.minio.io/).

For reference, our API docs are found [here](https://github.com/NebulousLabs/Sia/tree/master/doc), and Minio's docs are [here](https://docs.minio.io/).

Good luck! This bounty expires on August 31, 2017.

**Minimum Bounty Requirements** 
- Must deliver a working integration between Sia and Minio
- Must allow users to connect their rented storage on Sia to their Minio servers
- Minio Client must be given full control over file-related functions; users must be able to use the Minio client to upload/download Sia files.
- Can assume that the Sia node is already unlocked, funded, and has contracts.
- Code quality must meet approval from the Sia Core developers

**Comment by myusuf3** [comment]
This is all well and good to get things started, but what about when it's finished (bounty is collected) and people want updated features or support.

**Comment by nikshepsvn** [comment]
Exciting stuff -- can't wait to give this a go! Is there any way I can test stuff on the network without actually buying SIA? Is there a testnet?

**Comment by zachherbert** [comment]
@myusuf3 we have a few different options for that, and it could mean future bounties to update the integration, but we will discuss with the winning party.

**Comment by zachherbert** [comment]
@nikshepsvn you can take a look at https://github.com/NebulousLabs/Sia-Ant-Farm

**Comment by Ruffy1** [comment]
@zachherbert I have an incredible  good Product Idea for Sia which fits 100% to the company. Ho can i tell it to you? Have a nice day

**Comment by nikshepsvn** [comment]
@zachherbert Hey Zach, I looked at it and I'm still not sure how I would use Ant-Farm to test with Sia, is there any documentation I could go through?

**Comment by lukechampine** [comment]
@nikshepsvn: The basic setup is:

1. Install a `siad` binary in your path. `siad` should be compiled with the `-tags='dev'` build tag. This changes certain constants so that you can mine blocks with your CPU and send around fake coins. You can accomplish this by running the a bare `make` command in the Sia source directory.
2. Install the antfarm, create a testing directory, and `cd` into it. Copy `nebulous-configs/testing-stub.json` into the testing directory and rename it to `config.json`.
3. Start the antfarm with the `sia-antfarm` command. It will begin printing a bunch of log info, most of which can be ignored. If the ants aren't connecting to each other, make sure that all their ports are properly forwarded on your router.
4. The ants are now running a test network. You can interact with the network by issuing API calls to the various ants, or by connecting a new node to the network.

**Comment by nikshepsvn** [comment]
@lukechampine thanks for walking me through that! I'll give it a shot and let you know how it goes :)

**Comment by nikshepsvn** [comment]
"Minio Client must be given full control over file-related functions" Does this cover anything else other than upload/download?

**Comment by tuxillo** [comment]
Hi,

Does siad support any sort of "dry-run" mode where the file operations go to a local directory instead of having to get funds and contracts?

Regards,
Antonio Huete

**Comment by Mabiro** [comment]
@tuxillo : Just take a look at lukechampine's answer. Sia-Ant-farm would be the way to go.

**Comment by tuxillo** [comment]
Hi @Mabiro,

Yes I know, I was asking for something different.

Regards,
Antonio Huete

**Comment by lukechampine** [comment]
@tuxillo:

>Does siad support any sort of "dry-run" mode where the file operations go to a local directory instead of having to get funds and contracts?

not currently. But if you're just talking to the siad API, perhaps it wouldn't be too hard to mock the renter routes such that they write files to disk instead of uploading them to hosts. Otherwise, the ant farm is your best bet.

**Comment by harshavardhana** [comment]
Please reach out to us at https://slack.minio.io for any questions on Minio. We can help with the tool to test and validate.

**Comment by dvstate** [comment]
Hello,
On July 21, I submitted my solution, which met the requirements set forth in the bounty, to the Sia team via their Slack channel. I've been working with them on testing and enhancements since that date.

What I did was add a new gateway to the Minio server codebase for the Sia network. The Sia gateway communicates with the Sia network using a custom package that I also developed, called SiaBridge. The SiaBridge package provides a simple Go interface for storing and retrieving data on Sia. It also utilizes a built-in caching mechanism to drastically reduce latency.

This solution finally makes it possible to publicly share files from the Sia network!

At this time, basic functionality, such as creating and deleting buckets, and uploading, downloading, and deleting files using Minio's "mc" command line tool and Minio's web-based interface have been demonstrated to the Sia team and a few other developers.

For anyone wishing to get this up and running:
- Get my SiaBridge package: "go get github.com/dvstate/siabridge"
- Clone my forked copy of Minio server to your $GOPATH/github.com/minio/minio directory:
   cd $GOPATH/github.com/minio
   git clone https://github.com/dvstate/minio.git
- Checkout the sia_integration branch:
   cd minio
   git checkout sia_integration    
- Build Minio using Minio's Makefile:
   make
- A minio executable should be built in same directory. Run it and verify Sia gateway:
   ./minio gateway -h
- Actually start the Minio server with Sia gateway:
   ./minio gateway sia
-  You can then use it according to on-screen instructions with web browser or Minio client.

If anyone runs into any issues, just let me know.

Thanks,
David

**Comment by zachherbert** [comment]
Thanks @dvstate! We are testing, but everything is looking great with your submission. We will officially announce when testing is complete and code is reviewed by Sia and Minio devs, but for now you are our unofficial winner!

**Comment by Mabiro** [comment]
@dvstate 
Hi David, 
I've been talking with @harshavardhana from minio and showed him your submission. He is expected to look deeper in it today, but I think there were things he would prefer to be done differently. 

I suggest you go on their slack (https://slack.minio.io) and get his opinion of your gateway.

We should guarantee this way that the solution both works and respect the vision of the minio team.

**Comment by dvstate** [comment]
@Mabiro, I'll join the Minio slack shortly, and I'll be happy to work with any member of the team to improve the integration. Thanks!

**Comment by dvstate** [comment]
ANOTHER ROUND OF UPDATES:
Due to drastic code changes, the latest update is on the “sia_integration_v2” branch at: github.com/dvstate/minio
My SiaBridge package is no longer required. No part of it should be considered in this bounty.
Updates:
1.) Now uses Minio’s ObjectLayer for better filesystem management.
2.) Multipart uploads should now be supported.
3.) Bugs relating to 0 byte downloads and other errors with Minio Browser should be fixed.
4.) Better cache management.
5.) Minio uploads are now GUARANTEED to be uploaded to Sia. It no longer uploads from cache in background.
6.) Ability to enforce maximum cache size.
7.) All tunable parameters can be set via environment variables. They are all listed below with default settings.

SIA_CACHE_DIR: .sia_cache
SIA_CACHE_PURGE_AFTER_SEC: 86400
SIA_DAEMON_ADDR: 127.0.0.1:9980
SIA_DB_FILE: .sia.db
SIA_MANAGER_DELAY_SEC: 30
SIA_UPLOAD_CHECK_FREQ_MS: 3000
SIA_CACHE_MAX_SIZE_BYTES: 10000000000

Again, this is the “sia_integration_v2" branch. To get up and running:

cd $GOPATH/src/github.com/minio
git clone https://github.com/dvstate/minio
cd minio
git checkout sia_integration_v2
make
./minio gateway sia

Then point your web browser to the address printed to test with Minio Browser.

Please test away.

**Comment by zachherbert** [comment]
Thrilled to award the bounty to @dvstate! Congratulations! You can see the integration here https://github.com/dvstate/minio. Please post any issues to dvstate's repo, or ask questions on the #bounties channel in our Slack! Thanks all.

**Comment by harshavardhana** [comment]
Great news @zachherbert

**Comment by harshavardhana** [comment]
Thanks @dvstate

**Comment by mtlynch** [comment]
Will the Sia extension to minio be integrated from @dvstate's fork into the main minio repo?

**Comment by zachherbert** [comment]
The Minio team is deciding that. @harshavardhana will let us know!

**Comment by ckcollab** [comment]
For reference you can see the PR here: 
https://github.com/minio/minio/pull/4802

Thanks so much for all the hard work! :)

**Comment by harshavardhana** [comment]
> The Minio team is deciding that. @harshavardhana will let us know!

We have decided on including this upstream and the functionality/PR is currently under review. 
It will be available in one of the future releases as part of the standard product.
