### ISSUE TITLE
Contracts and uploaded files are not recovered on fresh install

### ISSUE THREAD

**Issue by eschnou** [NebulousLabs/Sia#2193]
1. Get contracts and upload files with sia
2. Delete (rename) sia folder (~/.config/Sia-UI on Linux)
3. Resync blockchain
4. Recover wallet from seed
5. Look in the files/contracts tabs

_Current result_: a fresh install with recovered wallet from seed shows 0 files uploaded and 0 contracts.

_Expected results:_ I would expect SIA to store somewhere on the blockchain or in the sia cloud the references to my contracts and uploaded files (encrypted of course, for example signed with a key derived from the wallet).

Without this, it means it becomes extremely critical to backup some folders (which one ??) from sia, otherwise **all is lost if disk/machine is lost**. While the whole point of distributed cloud storage is to make data always available :-)

This seems like a deal-breaker for using Sia as a storage for a cloud backup solution. Documentation should also be updated to make this clear and provide clear backup instructions to users.

**Comment by S-anasol** [comment]
Contracts saved only locally by host and renter.
To save it you need backup/restore renter folder.

Current Sia usage not allow using same seed on multiple wallets.
Same for renter and files.
Only in 1.3 added remote file repair without having local copy, but you should have renter files anyway.

But you still cant use it on multiple PCs at same time.

> distributed cloud storage is to make data always available
Files encrypted with private keys that only renter "can see" i.e. have saved.
So it cant be restored if you lost wallet files.
And renter private keys generated separately from wallet seed, so even seed cant help restore it.

**Comment by S-anasol** [comment]
So unfortunately you have lost your files and contracts.
not sure about money in allowance, can be returned probably after allowance will end.

**Comment by eschnou** [comment]
Hi Alex,

This is really bad and not expected for a cloud storage solution :-(

- Where are the renter files located ? What needs to be backed up ?
- Do you plan to fix this (by saving contracts/renter files securely in the blockchain or network ?)

I can update the documentation and send a pull request if you want.

**Comment by S-anasol** [comment]
> Where are the renter files located ? What needs to be backed up ?

~/.config/Sia-UI/sia/renter

> Do you plan to fix this (by saving contracts/renter files securely in the blockchain or network ?)

Im not a Sia dev.

But how can be public blockchain secure for private keys? :)
Of course need chain it with seed firstly, but anyway putting into blockchain private keys, even encrypted wont be secure.

https://trello.com/b/Io1dDyuI/sia-public-roadmap
I dont see such plans.

**Comment by eschnou** [comment]
It is in fact on the roadmap for next 18 months:

Ability to recover your files using only your wallet seed - https://trello.com/c/qTNXNNnm

**Comment by lukechampine** [comment]
The reason this is difficult is because a seed is not a lot of information. Recovering from just a seed requires a way to translate a seed into 1) all the contracts you formed with hosts *and* 2) the metadata of all the files you've stored on the network. And we need to do so in a decentralized way; it would be cheating to use your seed as a password on a Nebulous-owned server that stored all your metadata.

In the meantime, we can try to do a better job of managing expectations.

**Comment by S-anasol** [comment]
@lukechampine why dont use same private key generation scheme as for address hash?

i.e. generate contract keys from seed's private key + latest index.

In this case we can easily restore renter private keys at least.

But restore latest contract revision/files bit harder anyway :(

**Comment by lukechampine** [comment]
you need to "bootstrap" yourself somehow. One way would be to store something in blockchain, using `ArbitraryData`. Then you could scan the blockchain for a special string derived from your seed. `ArbitraryData` isn't large enough to hold all your file metadata, but perhaps it could store metadata for a single sector. Then you'd download that sector, and it would contain metadata for all your other files, or for more layers of sector metadata.
The tricky part would be keeping everything up-to-date. You need the Merkle root in order to download the sector, and the Merkle root would change every time the sector changed. Perhaps we could add a special case to the hosting code, so that you could request "Merkle root 0" (or some other reserved Merkle root) which would point to the special metadata sector.
I'm just spitballing here though. @DavidVorick knows the full plan, we just need time to flesh it out and implement it.

**Comment by S-anasol** [comment]
> One way would be to store something in blockchain, using ArbitraryData

Doesn't seem to be real use arbitrary data.
Even for single sector, there is too many renters to keep all needed metadata.
I see it will be like infinite queue to add some arbitrary data.

> The tricky part would be keeping everything up-to-date. 

Thats exactly what i mean too :)

This is actually thing i really want to see in blockchain, contract transparency. At least as siahub maintainer/data miner :)
Since now blockchain contains only metadata of contract creation and nothing more until contract finished(latest revision). Or something like.
I dont see any privacy problems with keeping up-to-date contract data in blockchain i.e. uploaded size/contract size/Sc amounts etc.

**Comment by lukechampine** [comment]
>I dont see any privacy problems with keeping up-to-date contract data in blockchain i.e. uploaded size/contract size/Sc amounts etc.

It's not so much a privacy thing as a scalability thing. The reason we form payment channels with hosts is so that we can perform negotiation fast, off-chain. Storing it on-chain would bloat the blockchain and slow down the revision process. Either you store every revision (slow, lots of data) or you store revisions infrequently (which means they can be outdated).

You'd also have to store the Merkle roots associated with the contract, and those take up much more space than the `types.FileContractRevision` type.

**Comment by S-anasol** [comment]
> Storing it on-chain would bloat the blockchain and slow down the revision process.

thing that really bloating consensus/blockchain is using json :D (not sure thats actually storing full json objects everywhere, but looks like it at least partially)

But ofc, Im not talking about total removing off-chain negotiation in favor of on-chain.
Just make some backup channel mechanism for contracts and save contracts data in blockchain more than 2 times(start, end) and store enough data to restore it of course.

**Comment by tbenz9** [comment]
This is a well known limitation of Sia and will be improved upon in later versions.  The Dev team is actively working on a solution to this issue.

Recommendation to devs: Close.

**Comment by lukechampine** [comment]
I'll open a separate issue (referencing this one) once we are ready to begin implementing this feature.
