### ISSUE TITLE
Architecture Week

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#234]
Things that we should discuss:

- Interfaces: How do the various components interact with the state?
- Components: What methods make sense?
- Mutexes: Who is responsible for locking/unlocking a mutex?
- Errors: How much context should errors have? Who is responsible for displaying the error?
- Panics: Where (if anywhere) is it acceptable to panic?
- API: how can we synchronize API changes across both siad and siac?

Feel free to add more.

**Comment by DavidVorick** [comment]
- API: what gets exposed? What do we use as passthrough? How much does the golang do for you vs. what does it expect to receive? (I'm expecting we'll do a complete re-write of the api in a few months - I feel very new to it)

- Save/Load/New conventions for persistence. The State should really be seen as a module and maybe even we should make an interface for it?

- Interfaces as a form of documentation vs. flexibility. I've really implemented the modules at this point to provide a clean documentation of exported stuff. I guess it was a bad move. I remember one of the other things that really motivated me to make the interface was that I was having circular import problems. The core was importing the modules, and the modules were also importing the core for some reason. I don't think they do that anymore. (They needed eachother?)

At the same time, it's nice to think of each component as being able to be swapped out for other stuff. Except the core does less and less and you start to wonder if it's even needed anymore? Should we design components to always be exposed? When exposing components, the things we typically try to protect are the configuration variables. Are those things that should be protected? The other modules/components do need to be looking at each other, which tends to expose the configuration stuff anyway. Ironically, I think the daemon can just replace the core, and we can move 'modules' to a top level directory with a bunch of sub packages, and 1 file for each interface.

I like the idea of having the modules regulate all of their own complexity. Maybe each module should even expose it's own api handlers, as opposed to having the daemon do everything? (probably not though). You just spin them up and they exist in their own world, and request things from each other and do stuff as you ask them.

- File staging: We want to support low latency stuff, but we also want to support high latency stuff. Especially when the network is in the early days, there might be glorious volumes of downtime. This means that recovering a file could take a while. Need a way to upload it, erasure code it, encrypt it, and send it out. If you're doing a 20GB file at redundancy of 4, you've got 80GB of stuff to manage. We need to make sure we can erasure code it, encrypt it, and ship it to a bunch of different hosts without needing extra workspace on the disk. You'll have to do every part of the process in memory, which is rough because you'll need to get the merkle hashes of everything before you can make the contracts.

- General Robustness: Read a thing about biological robustness and general system robustness. And the successful strategy seems to be a silly amount of redundancy and failure tolerance. Trees can lose 30% of their branches and still recover. Humans can lose 30% blood and still recover. A huge portion of your liver can go and you'll be okay. Basically, if you want a good network that'll survive any problems, make each part self-sufficient and able to route around the outages of any other part. I think this should apply to our programming style as well. Bugs are less of a problem if you need a chain of 3 or 4 things to all go wrong at once, especially if the system is self-repairing. That's why I'm really against panics in the code, one bad function can knock out the whole program, when really it could just return an error and everything else could work around the issue.

**Comment by lukechampine** [comment]
Good talk about Go design decisions (from the guy who wrote Cobra): http://www.slideshare.net/spf13/common-mistakes-in-go

**Comment by DavidVorick** [comment]
What do we have that's considered still needs to be done for this?

I would like to see the network/peering stuff reorganized.

Do we want to split siad into a 'main' and a 'meat' package? The main would probably be just one or two files, and the meat package would be the rest. But then siad would be a library instead of purely an executable, which I think makes sense.

The renter/host/hostdb all need to be brought back alive so the api is working again. There is still some work to go on this.

Is there anything else? I think that we've mostly cleaned up a lot of this in a good way.

**Comment by lukechampine** [comment]
I don't see a lot of value in having a separate siad package. I'd prefer to split off an API package, because it would be useful to both siad and siac.

network will probably wind up as a module. I'm not sure that this will have many benefits besides removing a folder from the top-level, though. I suppose the consistency is nice.

**Comment by DavidVorick** [comment]
lol we're still not done with this part.

Things got disorganized a bit when I went ham on the consensus package but I think it was the right time to do that.

**Comment by DavidVorick** [comment]
I'm going to consider this finished now that the gateway has been moved out. All that potentially remains is splitting main and siad, but that can be considered maintenance instead of architecture.
