### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia#2473]
Bug Report
==========

I'm testing out the Minio integration by uploading a bunch of files through Minio. It looks like it worked for ~7 hours and then crashed with `fatal error: concurrent map read and map write`.

I was uploading about 300 files at the time.

**Stack Trace or error message**

https://gist.github.com/mtlynch/2d7e2d693a6dfdef4ea8b934f80a6aed

* Sia version: `master` branch @ aacc30609e3bfc18baa2b1cf3cd89bd457a3715c
* OS: Ubuntu 16.04.3 LTS

**Comment by tbenz9** [comment]
Might be related to #2217.

Recommendation to devs: "Bug"

**Comment by lukechampine** [comment]
This looks like a relatively simple race condition caused by not holding `r.mu` when accessing `r.tracking` [here](https://github.com/NebulousLabs/Sia/blob/aacc30609e3bfc18baa2b1cf3cd89bd457a3715c/modules/renter/files.go#L234). A PR for this would be appreciated -- should be just a few lines of code.

btw, this is not related to #2217. Although they are the same class of bug, #2217 is caused by concurrent access in the api, whereas this bug is caused by concurrenct access in the renter.

**Comment by DavidVorick** [comment]
@mtlynch thanks for finding the issue, for fixing it quickly, and @lukechampine thanks for getting it merged quickly.
