### ISSUE TITLE
the  reason of sia pocket synchronizing to 89% and stop?

### ISSUE THREAD

**Issue by nighthurt** [NebulousLabs/Sia#2529]
the issue show that:
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 224.0998178 seconds

please reply to my e-mail(rongfy@greatwall.com.cn) ,thank you.

**Comment by tbenz9** [comment]
Can you post the logs? If you are using the Sia-UI press Ctrl+Shift+L and a new screen will appear where you can select and read them.

I would also recommend you ask for help in the Sia Discord, they will be able to help you in real time instead of waiting for a response here. https://discord.gg/sia

There is nothing actionable on this issue right now.  I'm closing it for now and will re-open it if logs or additional information is added.
