### ISSUE TITLE
Extend the API to support partial downloads

### ISSUE THREAD

**Issue by tbenz9** [NebulousLabs/Sia#2561]
Extend the API to support partial downloads.  This has been implemented on the backend but needs the API endpoints put in place.

**Comment by tbenz9** [comment]
If you offered some direction this might be an issue a community member would be able to handle.

**Comment by omidaladini** [comment]
I could take on this one; Is it about `/renter/download/` and `/renter/downloadasync/` routes supporting standard HTTP range requests? Interestingly, the HTTP API already supports `offset` and `length` form params but not the standard `Range` header.

**Comment by Fornax96** [comment]
I recommend using the Byte range HTTP header instead of custom URL parameters as described in the HTTP 1.1 spec: https://tools.ietf.org/html/rfc7233#section-3

Basically what this means is the server should reply with `Accept-Ranges: bytes` when the client makes a HEAD request. Then when the client makes a GET request it sends a `Range: bytes=1000-2000` header and the server sends a byte stream of bytes 1000 to 2000. This also immediately enables audio/video streaming as browsers use this header for buffering.

**Comment by Bojak4616** [comment]
It looks like this is no longer slated for v1.3.2 since a RC has already been released. May want to update to v1.3.3

**Comment by tbenz9** [comment]
I'm going to close this issue as I don't think it serves any real purpose.  I opened it hoping a community member could take on the task, but the core devs are actively working on the feature request.  Any further discussion should take place on Discord or via the PRs as they are submitted.
