### ISSUE TITLE
AcceptBlock && FutureBlockErr

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#262]
I realized it's not secure (for DoS reasons) for the state to resubmit future blocks to itself. Instead, whoever calls AcceptBlock should look for a future block err and handle it themselves (by waiting and resubmitting the block later).

It's kind of an unfortunate way to manage things, but hopefully it's only the network module that's worrying about it. The other one would be miner, but miner does error handling differently anyway.

**Comment by lukechampine** [comment]
Future blocks are an attack vector, because you can choose a "just right" timestamp that results in a large minority of miners rejecting the block (but not a majority). So you can't just drop all blocks past a certain cut-off; you have to keep them around and try to resubmit them when their timestamp becomes valid. On the other hand, you can't keep those blocks around indefinitely; that's an attack vector by itself.

I propose the following logic for handling future blocks:
- If a block's timestamp is too far in the future, add it to the "FutureBlocks" set.
- When the timestamp of a block in FutureBlocks becomes valid, resubmit it and remove it from the set.
- If a block in FutureBlocks has not become valid after the state has accepted X new blocks (6?), remove it from the set without resubmitting it.

**Comment by DavidVorick** [comment]
Hmm. It's definitely a tricky problem. There are two issues:

1. You need to make sure that a miner will be on the longest chain as soon as it hits maturity, we want to minimize the amount of desynchronization a miner will have if the network is attacked using some kind of a future attack.

2. We have to make sure it's expensive for people to store future blocks on the network, otherwise they can have 200,000 future blocks waiting at one time and bad things will happen to our nodes.

I'm thinking:

1. future block must have a valid amount of work, and must extend one of the recent 6 blocks.

2. we call 'synchronize' immediately after accepting a new future block (as long as the error is 'not longest chain error' or something).

3. we only keep future blocks that are at most 'futurethreshold * 2' into the future. father away ones just get tossed.

This will make it expensive to fill up nodes with future blocks, because each block will need a unique set of valid POW, and that's costly to the attacker. If an attacker can fill nodes with more than ~100 future blocks, they can 50% attack the network, and this attack is suddenly the less interesting problem for the network.

Synchronizing immediately after getting a future block means miners aren't at risk of getting left behind for only storing 1 future block.

**Comment by DavidVorick** [comment]
Fixed in #530 

I regret taking so long to get to this.
