### ISSUE TITLE
problem after problem, not being addressed

### ISSUE THREAD

**Issue by ktmine** [NebulousLabs/Sia#2677]
I have a problem of not being able to open/use the Sia-UI on my computer.  I submitted my issue here as the UI directed, when the UI closes unexpectedly.  

The response that I was given was that I was told to reboot my computer and join discord website. Then my issue was closed.

As I browsed the closed issues to look for my issue I discovered many other people that had the same issue, Sia-Ui closed unexpectedly.  After reading some of them, I observed that they too had been closed without a resolution.
  
I still cannot use the Sia-UI and I dont want to give up on Sia.  How many of these other people who had an interest in Sia now have given up? I am not a programmer, but I am someone that thinks Sia is a good idea and would like to use it.

We each followed the instructions when our UI's crashed and did not receive any help.  I wonder how many of the people who couldn't get their UI to work will never use Sia again?  How many others didn't submit an issue and just gave up instead?

I didn't want to sign up to submit an issue here, but I did, now I am told to sign up to another web site (discord) to get help.  

Please help us non-programmers to be able to use Sia on our machines, or lose a bunch of users.

**Comment by lukechampine** [comment]
If you do not plan to be a host, there's a workaround for this.

Navigate to the folder with Sia-UI.exe, then open the file `resources/app/dist/renderer.js`. Find this section of code:
```js
const siadProcess = __WEBPACK_IMPORTED_MODULE_1_sia_js__["launch"](siadConfig.path, {
        'sia-directory': siadConfig.datadir,
        'rpc-addr': siadConfig.rpcaddr,
        'host-addr': siadConfig.hostaddr,
        'api-addr': siadConfig.address,
        'modules': 'cghrtw'
});
```
And delete the letter `h` from the last line, so that it reads:
```js
        'modules': 'cgrtw'
```
The next time you run Sia-UI, it will run without the host module, which is the module that's crashing.

Sorry that you've experienced so much trouble. The bug in question seems to be a result of Window's file renaming semantics being different from Linux and Mac. Unfortunately we don't have the resources to investigate it immediately, but we are planning to give the host module a much-needed overhaul.

**Comment by tbenz9** [comment]
Sorry you've been frustrated with your experience.  Discord is the best place to get help, that's why I sent you there first.  You also have the option of re-opening any GitHub issues you feel were closed without a proper resolution.

Since lukechampine offered a solution I'm going to close this issue.  If you are still having issues and don't want to ask in Discord, please re-open this issue.

**Comment by ktmine** [comment]
Thanks, that worked to get it to open. I would like to host in the future so Ill wait for the next update. 

Thanks very much for getting back to me.
