### ISSUE TITLE
Add brute-force seed check to siac

### ISSUE THREAD

**Issue by tbenz9** [NebulousLabs/Sia#2707]
# Feature Request
Create the `siac wallet fuzzseed` that attempts to brute-force alternate words in a seed, check the checksum, and return seeds that are valid.

**Background (From Discord conversation):**
**Nemo:**  it should be possible to recover the seed fairly quickly, because seeds contain a checksum. So you just need a script that tries to insert every word in each position, and then checks that the checksum is valid.
**Taek:** we should probably just bake that into siac; have a siac wallet fuzzseed or something.
It'll take your seed, brute force check alternate words, check the checksum, and if the checksum works out it'll throw it at siad. It'll go up  to 2 substitutions I think without too much effort

Dictionary of (English) words: https://github.com/NebulousLabs/entropy-mnemonics/blob/master/english.go

**Comment by Olione1** [comment]
Hi, here! 
I posted on discord my issue..I created a siawallet, didn't backup correctly (28words instead of 29 !)
..and sent coins from bittrex to that adress in the meantime...I have the Tx infos...
So I opened a new wallet, verified everything, and would like to recover my 1st adress (in sia wallet, "recover seed"?!)...
As I have 28words from seedphrase, 1 from dictionnary is missing, That makes around 44000 possibilities,....I'm looking for a way to automate that research...Thank you so much...
I'll be glad to share some SC !!! ;)

**Comment by lukechampine** [comment]
Huh, I figured I'd just release this as a separate script, like we did with `recover-wallet` and other scripts.

In order to avoid duplicating the word list, the first step here would be to export the `englishDictionary` variable (and other dictionary variables) in `entropy-mnemonics`.

In the meantime, here's a script that should do the job: https://gist.github.com/lukechampine/0c9c9351a10f7defffcb4196942728ec

**Comment by tbenz9** [comment]
I don't want to introduce too much scope creep, but I'm remembering that some users had issues with words being split at the wrong place.  I think the example was "uphill" was split into "up" and "hill".  Maybe we should add some error checking to make sure all the words are in the dictionary.

The other common situation is when a user has whitespace before, in the middle, or at the end of their seed, that should be fairly simple to trim out.  We might consider doing this on all seed functions.

**Comment by Olione1** [comment]
First hank you!...and second, I need "a hand" on how to do! 
...I guess I have to put the 28 words I have in here  : **fmt.Print("Enter partial seed: ")**
and then, where do I copy this script?! Sciawallet terminal?Applescript?.
I'm really a beginner... :) Thanks for your patience!

**Comment by Olione1** [comment]
Ouch, I don't see my last comment...
So what should I do with this script?...enter it in applescript? or Siawallet terminal?
And where do I have to enter my 28 words?!...
Thank you for your patience,...

**Comment by lukechampine** [comment]
@Olione1 download the Mac binary listed at the bottom and run it in Terminal. Enter your partial seed at the prompt, and it will search for the full seed.

**Comment by Olione1** [comment]
Hi, Luke, thank you a lot,...but with my poor English and knowledge in
progra(= to +- 0 ! ), I need more indications......
SO I have to copy the script(?!), replacing the "enter partial seed" by my
28 words, and then execute in applescript, is it?! (also prompt doesn't
mean a lot for me?!)
Thanks a lot for accompanying me in this research! ...
Namaste!
Oli.


2018-01-31 5:52 GMT+01:00 Luke Champine <notifications@github.com>:

**Comment by Olione1** [comment]
ok,sorry, I got the prompt...so, in this terminal I run the script, placing the 28words in "enter the partial seed" field?...is it?! 
We're almost there! :)

**Comment by Olione1** [comment]
Ok,...found with a dev friend!!!...It's scanning the blockchain..result soon! :)

**Comment by Olione1** [comment]
MMMhhh, got the same error message...it seems strange 2me that the result has 2* the same word...

**Comment by Olione1** [comment]
I make another scan to verify...
...

**Comment by Olione1** [comment]
![capture d ecran 2018-01-31 a 20 21 01](https://user-images.githubusercontent.com/35978488/35643935-fd6e01da-06c7-11e8-9874-92f02b05d8a7.png)
gosh...

**Comment by Olione1** [comment]
when I go to console and typ sia, this msg appears..
![capture d ecran 2018-01-31 a 20 31 12](https://user-images.githubusercontent.com/35978488/35644794-4521a598-06ca-11e8-9fdd-d69fcd4252c6.png)

**Comment by Olione1** [comment]
Justa asking...maybe could we try taking the words of partial seed out from the bigliste?!...cause honnestly, 2* the word salads side by side, I would have remember !!! :)

**Comment by Olione1** [comment]
Still waiting for an answer of bittrex...I can't figure out why they're so slow... :(

**Comment by tbenz9** [comment]
I'm going to close this.  I think I agree with luke that this type of utility is probably best done outside of Sia.  If anyone feels strongly one way or another please feel free to re-open this issue.

**Comment by Olione1** [comment]
Hi, I have ran the script and have a seed phrase of 29 words, though.
One thing strange is that I got a result containing 2 same words side by
side....is it ok?!
...I couldn't find the wallet entering my new seed phrase in sia wallet;
...according to a dev from sia (because my transaction doesn't appear in
siaexplorer), it's probably not confirmed and it's not appearing as being
in my wallet...so, according to him again, I won't be able to sweep the
wallet as there's nothing in it.
I wrote a mail to bittrex(several, actually) to ask what with the
transaction, but got no return atm....
Is it possible for you to track a transaction?!...I mean to know, with the
address, what happened or where are my siacoins?
Just in case I give you the datas of this transaction from bittrex to sia
adress :
01/13/2018 SC 5010.00000000 Completed


   - *Address:*
   d319d0ce3333c9ce36b36a3255f27ab89fc813fc24fb23326af64d26ba5f76b7f8440f852f8d
   - *TxId:*
   497b2be2abd409d6a0d6b48d3f09f3c36bebfb576edd98358af3b3ee4aff9f5c

..as you see it appears as completed in bittrex...?!
I have to say at this point I'm stucked....
Thanks for all ...Hope it will be solved one of these!
All the best !
Oli.




2018-02-17 1:16 GMT+01:00 Thomas Bennett <notifications@github.com>:
