### ISSUE TITLE
Sia UI wallet not receiving coins

### ISSUE THREAD

**Issue by Kaster8** [NebulousLabs/Sia#2724]
I just recently started mining Sia and got my wallet setup. Everything looks good and I have been receiving payments fine through the siamining.com. I am however missing a single transaction that won't show up on my wallet. It has since received a few other payments fine. The TX id is 5a007ead22d17de0b1864ea35ed729b9048ade665b276f2ad7b8ca5bb7d7799f and my specific transaction for 2177 coins is on output id https://explorer.siahub.info/hash/c1c7559dc4e08f949cdf279c45a81b3a0edabb44675bb517ed1ea57b33ddaaeb .  I have tried restarting my wallet with no success and running the consensus command in CLI shows that I am synced.  If I try to run the wallet sweep command it gives an error  "Seed: Reading seed failed: The handle is invalid" . Or if I click on the recover seed button in the wallet I also get an error showing "error when calling /wallet/sweep/seed: cannot sweep primary seed". 

Sia version: 1.3.1 
OS: Windows 7 Pro 64bit

**Comment by Bojak4616** [comment]
Try this solution https://github.com/NebulousLabs/Sia-UI/issues/581#issuecomment-299747969

**Comment by tbenz9** [comment]
If you continue to need help I recommend you join the #Help channel in the Sia Discord.  The GitHub issues are not the appropriate or best place to ask for help unless you have a specific task for the Sia devs.  I'm going to close this issue since it doesn't have a specific action item for the devs and recommend you seek help through Discord.

I believe this is a relatively common issue that the devs are aware of and working on a comprehensive fix.  My understanding is that the SC are simply not being found by the wallet software when it scans the blockchain, they are putting in code that will occasionally rescan the blockchain to find orphaned transactions like the one you've shown.  The guys on Discord will know more.

**Comment by Kaster8** [comment]
Thanks to Bojak. I was able to resolve this issue with the trouble shooting that went on in the thread he pointed me to.
