### ISSUE TITLE
API bug: /renter/files returns "files": null when zero files exist

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia#2760]
# BUG REPORT

**Stack Trace or error message**

N/A

**How to reproduce it (as minimally and precisely as possible)**

Start siad
Call `/renter/files`

```bash
$ curl -A "Sia-Agent" "localhost:9980/renter/files"
{"files":null}
```

**Expected Behavior**

`/renter/files` should return `{"files":[]}`

**Actual Behavior**

`/renter/files` returns `{"files":null}`

From a client perspective, `null` is unexpected. It's more natural for it to return an empty array.

`/renter/contracts/` has intuitive behavior for this:

```bash
$ curl -A "Sia-Agent" "localhost:9980/renter/contracts"
{"contracts":[]}
```

**Environment**
* Sia version: latest master, as of 2018-02-12 (77bc1a0ac5a00a83e3cabc6ad788625a71966c52)
* OS: Ubuntu 16.04

**Comment by lukechampine** [comment]
this is due to dumb behavior in Go's JSON encoder. Basically:
```go
var slice []int
json.Marshal(slice) // => "null"
slice = []int{}
json.Marshal(slice) // => "[]"
```
Internally, the difference is that the first `slice` is completely zero-valued; the underlying pointer that normally points to the slice data is `0`. Whereas the second slice has a valid pointer, just with zero length.
There is some merit to encoding them differently, since otherwise, you can't distinguish between a missing value and an empty value. But for our purposes, we want `[]` pretty much everywhere, not `null`.
AFAIK our API docs don't specify whether such values return `[]` or `null`, so maybe we can get away with breaking compatibility here. If we do that, I'd like to do it everywhere `null` appears, and then commit to not introducing it anywhere else.
