### ISSUE TITLE
API request: Unexport low-level functions

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia#2774]
# FEATURE REQUEST

I notice that the [`node/api/client` package](https://github.com/NebulousLabs/Sia/blob/master/node/api/client/client.go) exports several low-level functions that clients shouldn't need:

https://github.com/NebulousLabs/Sia/blob/62752aad77c813518d1efa6a5943f9143692814d/node/api/client/client.go#L73

https://github.com/NebulousLabs/Sia/blob/62752aad77c813518d1efa6a5943f9143692814d/node/api/client/client.go#L103

https://github.com/NebulousLabs/Sia/blob/62752aad77c813518d1efa6a5943f9143692814d/node/api/client/client.go#L125

https://github.com/NebulousLabs/Sia/blob/62752aad77c813518d1efa6a5943f9143692814d/node/api/client/client.go#L157

I'd like to unexport these. I'm willing to do the work if the dev team agrees with this change.

# Flexibility

It's not too hard to imagine that Sia will want to make breaking REST API changes after version 1.

Ideally, we'd like clients to be able to write code against `/node/api/client` and never have to rewrite it. If we prevent clients from making these low-level calls, it's a lot more likely that we can abstract away breaking REST API changes in the library level so that the Go library clients don't need to rewrite any code.

Obviously some API changes might not be fixable within the library layer, but we're much more likely to preserve backwards compatibility in the library if we don't give callers this low-level access.

# Ease of use

These functions clutter `Client`'s interface. A good API should have just one way of accomplishing a task. These extraneous functions make it so that `Client` provides three equivalent ways of calling each REST API.

# Obscures bugs

Clients really should never need to drop down to this low of a level to use the Sia API. If they find themselves wanting to, that's a bug in the API and we should fix it by offering the functionality they need in the API itself, not by encouraging them to poke through the abstraction layer.

**Comment by ChrisSchinnerl** [comment]
Hm I guess you are @mtlynch. I started this [PR](https://github.com/NebulousLabs/Sia/pull/2782). @lukechampine and @DavidVorick what do you think?

**Comment by DavidVorick** [comment]
> Ideally, we'd like clients to be able to write code against /node/api/client and never have to rewrite it. If we prevent clients from making these low-level calls, it's a lot more likely that we can abstract away breaking REST API changes in the library level so that the Go library clients don't need to rewrite any code.

I agree with this, though I'm not sure how to provide that kind of flexibility in golang arguments. We could make the inputs to every function a struct, and because it's already to leave struct fields blank so long as you are using named fields, this would achiave 90% of the goal. But users could still write code (that doesn't use named fields) that breaks if we extend the API.

I am slow to agree to un-export the low level calls, because the `client` package is not complete in the sense that it does not wrap every api call. If you need an endpoint that we haven't wrapped yet, you either have to make feature request and wait, or implement these functions yourself. I would think that any PR which un-exports these functions would also need to make sure that this wrapper has 100% coverage of the API. Unless we want to move them to different packages, such as node/client/raw and node/client/direct or something. But that doesn't seem like a great solution either.

I also thikn that this package should be a relatively thin package. I would expect people using this package to be reading the API docs directly, otherwise we are going to need to duplicate the documentation around every endpoint. I want to make sure that the `client` package has the full power of the API available to it.

**Comment by ChrisSchinnerl** [comment]
@DavidVorick I think after merging the upload/download siatest PR the client library is pretty complete. I created a [PR](https://github.com/NebulousLabs/Sia/pull/2782) that unexports the methods and it seems to be a pretty straightforward change since we don't use the low-level calls a lot in the codebase.

**Comment by mtlynch** [comment]
I agree that a thicker package imposes more costs. It does mean writing a new set of documentation, and it does mean doing more work whenever an API endpoint is added.

I think the question then becomes how much do we value a good developer experience?

The quality of the library can easily make the difference between a developer building on top of Sia or rejecting it as too complicated.

I'm trying to imagine myself as a developer choosing among cloud storage providers. I read the [Google GCS library for Go](https://godoc.org/cloud.google.com/go/storage) and it provides clean, intuitive abstractions. I can write an app on top of GCS using nothing more than the information on that single page.

If I then read the [Sia client library](https://godoc.org/github.com/NebulousLabs/Sia/node/api/client), I don't know what to do. If I want to do something straightforward like send Siacoins, none of the function names seem to indicate they support that. Even if I figure out it's `WalletSiacoinsPost` the documentation just says:

>WalletSiacoinsPost uses the /wallet/siacoins api endpoint to send money to a single address 

As a new developer, this woudln't make sense to me. Even if I dug around and find the documentation for the `/wallet/siacoins` REST API, now I have the challenge of figuring out how to how to generate a `types.Currency` and a `types.UnlockHash`, which are defined in a completely different package.

The decentralized nature of Sia makes a thousand things about it inherently more difficult than S3 or GCS. The library isn't one of those things. There's no reason why the Sia library can't be as easy to use as the GCS library.

Further reading: https://blog.spaceduck.io/new-sia-library/#a-very-thin-abstraction-layer

**Comment by lukechampine** [comment]
addressed by #2782
