### ISSUE TITLE
Trouble with the daemon on openrc-run based systems

### ISSUE THREAD

**Issue by ChadLWilliams** [NebulousLabs/Sia#2852]
# BUG REPORT

Based on the tutorial for a headless sia server on Ubuntu I've tried to convert the systemd init script:

```bash
Description=Sia Daemon

[Service]
ExecStart=/home/siad/Sia/siad
WorkingDirectory=/home/siad/Sia/
Restart=always

[Install]
WantedBy=multi-user.target
Alias=siad.service
```

To a script for openrc used on alpine (/etc/init.d/...). This is what I got so far.

```bash
#!/sbin/openrc-run

name="Sia Daemon"
command="/home/siad/sia/siad"
command_args=""
command_user="siad"

pidfile="/run/siad.pid"
start_stop_daemon_args="-d /home/siad/sia"
command_background="yes"

depend() {
        need net
}
```

Problem is that the deamon won't start, it crashes with the following error:

`listen tcp 127.0.0.1:9980: bind: cannot assign requested address`

This is on a clean system without additional software and no firewall that could interfer or block the connection. So basically, how do I run a headless sia daemon on Alpine linux?

Reproduce by folliwing the official tutorial for Ubuntu: https://forum.sia.tech/topic/17/howto-run-sia-host-on-headless-linux-server-ubuntu on a fresh copy of Alpine linux.

**Environment**
* Sia version: 1.3.1
* OS: Alpine linux (kernel: 4.4.120-mainline-rev1)

**Comment by tbenz9** [comment]
Hmm, I don't have an environment set up to troubleshoot this with you, but I would definitely check that `siad` is not already running.  Usually when it can't bind to an address it's because that address:port is already in use.  Are you able to start/stop `siad` directly from the command line (not through an rc script)?

**Comment by tbenz9** [comment]
Also just a FYI: We usually try to keep GitHub issues related to Sia core development bugs and feature requests.  This falls under more of a specific Linux configuration problem, and is probably not actually anything wrong with Sia itself.  If we can't figure it out I'm probably going to close this issue since as it stands right now there is no action for a Sia developer to take.

**Comment by ChadLWilliams** [comment]
Thanks for a quick reply, I checked some more and turns out I've made a newbie mistake. The address failed to bind due to the lack of a loopback interface. Here's how I got it working if anyone else has the same issue. I've opened __/etc/network/interfaces__ and changed:

```bash
auto eth0
iface eth0 inet dhcp
```

to this:

```bash
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
```

Now the daemon starts without issues. It works with the openrc script as well, tested on Alpine and Gentoo.
