### ISSUE TITLE
Why `FundSiafunds` requires a siacoin input of exactly 'amount'? I didn't see the necessity.

### ISSUE THREAD

**Issue by hupengbuaa** [NebulousLabs/Sia#2920]
As told in the codebase:<br>
```
// FundSiacoins will add a siacoin input of exactly 'amount' to the
// transaction. A parent transaction may be needed to achieve an input with the
// correct value. The siacoin input will not be signed until 'Sign' is called
// on the transaction builder.
```

I am working on build transactions locally, this part is not so intuitive for me.  Especially involving with building `A parent transaction` .Perhaps anyone can explain the philosophy under it.

**Comment by lukechampine** [comment]
Each input comes from an output, and outputs are "indivisible," i.e. you have to spend all of the coins in the output at once. So if you want to spend 10 SC, but you only have an output worth 15 SC, how do you spend it? The answer is a transaction like this:
```
Input:    15 SC (from the 15 SC output)
Output 1: 10 SC (sent to the destination address)
Output 2:  5 SC (sent back to your own wallet)
```
The 5 SC is known as a "change output." Basically, any excess value is sent back to your wallet.

However, `FundSiacoins` does something slightly different. As you mentioned, it creates an entire separate transaction, so the result is:
```
Transaction 1 (the "parent transaction"):
Input:    15 SC (from the 15 SC output)
Output 1: 10 SC (sent back to your own wallet)
Output 2:  5 SC (sent back to your own wallet)

Transaction 2:
Input:    10 SC (from Transaction 1)
Output 1: 10 SC (sent to the destination address)
```
The reason is does this is so that transactions can be constructed more precisely. That is, if I want to create a transaction that with one input worth exactly 10 SC, I should be able to do that. If `FundSiacoins` instead lumped everything into one transaction, then the value of the input would be larger than I expected and the transaction would have an extra output; this increases the total size of the transaction, affects the indices of the outputs (e.g. when calling `txn.SiacoinOutputID(0)`), and has privacy implications.

**Comment by tbenz9** [comment]
Looks like Luke answered your question.  Closing this for now, feel free to reopen it if you have other questions.

**Comment by hupengbuaa** [comment]
Thanks.   I want to make it more precisely with the mining fee:
```
Input:     15.1 SC(from the 15.1 SC output)
Output1:     10 SC(sent to the destination address)
Output2:      5 SC(sent back to your own wallet)
MinerFee:   0.1 SC(sent to the miner)
```
 Your illustration is very clear. But creating two transactions instead of one would probably cost more miner fees, right?  So Can I consider your implementation is optimizer other than necessity?

**Comment by lukechampine** [comment]
Indeed, creating a "parent" transaction will result in more miner fees. If you are constructing your transaction manually, and you don't care about putting all of the inputs and outputs in one transaction, then it is cheaper to do that.
