### ISSUE TITLE
Shouldn't the transaction_signatures be empty before applying the "Sign" method?

### ISSUE THREAD

**Issue by hupengbuaa** [NebulousLabs/Sia#2928]
I know the  `SigHash` method does some marshal work, but shouldn't the `transactionSignatures` field be empty before actually **sign** the transaction?  (or have a difference under  `multi-sig` case?)

https://github.com/NebulousLabs/Sia/blob/b94b333eb6b5cd918c6a5a09629b0423abcfc421/types/signatures.go#L181-L227
And the same thing in the `CoveredFields` construct.
https://github.com/NebulousLabs/Sia/blob/b94b333eb6b5cd918c6a5a09629b0423abcfc421/modules/wallet/transactionbuilder.go#L504-L546

**Comment by lukechampine** [comment]
I don't understand your question. Can you give an example?
Also, the best way to reference code is via a permalink: https://blog.github.com/2017-08-15-introducing-embedded-code-snippets/

**Comment by hupengbuaa** [comment]
Thanks for reminding. I've updated the content, and I kind of figure out that's for multi-sig.( right?) Appreciate your reply.

**Comment by lukechampine** [comment]
I'm still not 100% sure I understand the question, but I'll try to give some context.

When you want to sign a transaction, you first have to decide which parts of the transaction will be covered by the signature. In the vast majority of cases, you sign the whole transaction, but in other cases you'll only sign part of it. (For example, when exchanging contract revisions with a host, the renter only signs the contract revision, not any other part of the transaction.) To specify which parts you want, you use the `types.CoveredFields` struct.

Digital signatures typically sign a hash of the data instead of the data itself, because the hash is much shorter. To calculate the hash of the transaction data you want to sign, you call `SigHash`. `SigHash` looks up the `CoveredFields` and hashes all the parts of the transaction that it specifies. Once you have this hash, you sign it and add it to the `TransactionSignatures` array of the transaction.

A signature can't sign itself, but it can sign other signatures. I don't think this is super useful though; it doesn't occur anywhere in the Sia codebase. Sia does support multisig, but not by signing other people's signatures. Instead, a `types.UnlockConditions` can specify a number of signatures required, and a set of public keys that may sign. To spend such an output, you reveal the unlock conditions along with the appropriate number of signatures, each provided separately in the `TransactionSignature` array. Currently, there's no way to create a multisig output via the API, but you can construct one manually using a small Go program.

Hope this helps!

**Comment by hupengbuaa** [comment]
Your explanation is very helpful. I am working on building and sign txn manually now for SC wallet.  I found the code for marshaling `transaction_signatures`, but your answer suggests it won't be called. It seems I can pass over it in my code.

https://github.com/NebulousLabs/Sia/blob/b94b333eb6b5cd918c6a5a09629b0423abcfc421/types/encoding.go#L1051-L1059

**Comment by lukechampine** [comment]
In the vast majority of cases, yes, the covered fields simply set `WholeTransaction = true` and nothing else, which means no `TransactionSignature`s are signed. It is possible for a transaction to sign them, but if you don't plan to ever do that, you don't need to worry about it when writing your signing code.
