### ISSUE TITLE
`siac` fails to send SC with "Failed to parse destination address can't scan type: *types.UnlockHash"

### ISSUE THREAD

**Issue by jbrukh** [NebulousLabs/Sia#2973]
# BUG REPORT

Upon executing the following command, I get an error message.

    siac wallet send siacoins 100SC 2f68ba31fd1aa85e9409d07ba655cec52662baa6c5fb3d1ce79ae5ba434369430f598ebf0c22

**Stack Trace or error message**

    Failed to parse destination address can't scan type: *types.UnlockHash

**Expected Behavior**

To send siacoins and receive a transaction hash.

**How to reproduce it (as minimally and precisely as possible)**

Run the command above.

**Environment**

* Go: 

    ```$ go version```
    ```go version go1.10 darwin/amd64```

* Sia version: 1.3.2 installed with go (`go get -u github.com/NebulousLabs/Sia/...`). Notably, `siad` says:

    ```$ siad -M gtcw```
    ```Sia Daemon v1.3.2```
    ```WARN: compiled without build commit or version. To compile correctly, please use the makefile"```

* OS: Mac OS X High Sierra 10.13.3

**Comment by jbrukh** [comment]
Temporary fix was to downgrade to 1.3.1.

**Comment by lukechampine** [comment]
Looks like this was broken by https://github.com/NebulousLabs/Sia/commit/057f5ec270888641945ba1f0eceab914f286c34f, which uses `fmt.Sscan` to load the address. `types.UnlockHash` doesn't implement the `Scan` interface, so it fails. We can fix this easily by either implementing the `Scan` interface or using `LoadString` instead of `Sscan`. I've implemented the latter on the `addr-scan` branch if you want to build it from source right away.
