### ISSUE TITLE
Siad has exited unexpectedly

### ISSUE THREAD

**Issue by alexpoluks** [NebulousLabs/Sia#3093]
# BUG REPORT

**Stack Trace or error message**  Siad has exited unexpectedly

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version: 1.3.3
* OS: linux
Sia Daemon v1.3.3
Git Revision 910034d
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 6.345861722 seconds
2018/06/09 23:44:53 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2018/06/09 23:44:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2018/06/09 23:44:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2018/06/09 23:44:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms

**Comment by tbenz9** [comment]
This bug is being tracked at NebulousLabs/Sia-UI#670

It was previously tracked at #2406

There is no sure workaround that I'm aware of but you can try the instructions linked in the issues above. My understanding is this only affects MacOS. You can also try completely reinstalling Sia, only a small subset of users report this issue
