### ISSUE TITLE
Signature marshalling corner case

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#312]
Since the signature type is actually a pointer to 32 byte array, it encodes as 33 bytes.

I'm not sure if this is a problem.

**Comment by DavidVorick** [comment]
It means that `encoding.Marshal(pk)` is not equivalent to `pk[:]`, which is a property that might be desirable.

Same goes for signatures.

**Comment by lukechampine** [comment]
It doesn't seem like a technical problem, but I don't think it should be sent that way over the wire, unless there's a conceivable reason why a signature should be `nil`.
That reminds me...even though our Marshalling algorithm is well-defined, we're still going to have to write a specification that spells out exactly how each type is encoded. This is especially important if, e.g., we switch to a new signature algorithm, because everyone needs to agree on how it will be encoded.

For now I would just dereference the pointer before encoding it. But a more radical alternative would be to simply ban `nil` pointers from being encoded. Then pointers just encode to what they point to. I don't know if there are any `nil` pointers in consensus types, but I imagine there will be when encoding other local types (stuff that gets saved to disk). So this may not work. Or we may just decide not to use the same marshalling algorithm for local stuff.

also...pls spellcheck your issues, since you can't fix them silently afterwards :P

**Comment by DavidVorick** [comment]
huh. We should tell github about the corener case of misspelled issue titles.

**Comment by DavidVorick** [comment]
Right now, it seems sufficient to ban `nil` from being sent over the wire. Except for the strings of arbitrary data, I can't see what would cause problems.

We do all the signature stuff with pointers because that's how the crypto library has it. I'm not sure if there's a sidechannel based reason to do it that way, but I imagine so. (Not that it matters for public keys and signatures, but still)

**Comment by lukechampine** [comment]
Arbitrary data should be an issue either, since it doesn't involve pointers. (`""` is encoded as a length prefix of 0).

Are there potentially `nil` pointers being used in other types that are encoded? Like the state?

**Comment by DavidVorick** [comment]
block nodes don't get encoded. All the types should be pointer free, at least as far as sending consensus objects over the wire goes.

That might mean we need to adopt a different strategy for saving to disk though.

**Comment by lukechampine** [comment]
that's what my second paragraph said lol.
I'll wait until we have a DB to decide though.

**Comment by DavidVorick** [comment]
I'm just going to remove the pointers from our types in package crypto.
