### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by 9ezcore** [NebulousLabs/Sia#3127]
# BUG REPORT

**Stack Trace or error message**

**Expected Behavior**

**How to reproduce it (as minimally and precisely as possible)**

**Environment**
* Sia version: 1.3.3
* OS: windows

I want to solve this problem, too. I've been trying to install Sia-ui for days, but it doesn't last for hours on the loading page. I've deleted and re-installed the UI, but the results are the same. What should I do?
It is too difficult for ordinary people who are unfamiliar with programming to use.

Error content
"Loading can take a while after upgrading to a new version. Check the release notes for more details."

**Comment by tbenz9** [comment]
That message is normal when you reinstall, upgrade, or install Sia for the first time.  Have you tried letting it run for a few hours?

You can also try to access your log messages using this self-help guide: https://gist.github.com/tbenz9/8066d74853ab28c23bd7bc1d3c7cdeda

I'm going to close this issue for now because there is insufficient information for the devs to do anything.  If you continue to need help I recommend you join the Sia Discord server and ask for help in the #HELP channel.
