### ISSUE TITLE
Proposal: Testing conventions

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#317]
All packages should have internal testing that brings the coverage to 100% (except intentionally unreachable code).

All testing should be done using exported functions only. Furthermore, these functions should only be exported if they are intended to be used by other packages, meaning we plan to maintain support for the function calls.

**Comment by lukechampine** [comment]
Sounds good, but won't it be difficult to reach 100% only using exported functions?

**Comment by DavidVorick** [comment]
hopefully not. If you can't reach certain codepaths using exported functions, then why are the codepaths there?

I'm hoping that this approach to testing encourages more critical thinking about the layout of the package and the flow of the logic. It'll be easier to know once we've given it a try.

**Comment by lukechampine** [comment]
true, I'm just guessing it will be harder to trigger certain code paths because you'll have to, e.g., line up a bunch of functions in just the right sequence. And if you want to trigger the other code path, they have to be in a slightly different sequence, so you need to start over from scratch.

I actually like this approach though. As you say, it should give us a good deal of feedback about the package design.

**Comment by DavidVorick** [comment]
I'm having a hard time with this. It's not the reaching codepaths that's the problem, it's the verifying that everything changed correctly. Perhaps that's because right now the consensus package is a bit opaque to the external world.

**Comment by DavidVorick** [comment]
TODO: Watch a bunch of videos about TDD to learn more, and then check back.
