### ISSUE TITLE
siad loading transaction pool

### ISSUE THREAD

**Issue by snehap007** [NebulousLabs/Sia#3187]
Hello,
I launched sia daemon using siad. its connect successfully but when I call consensus API always getting synced: false.  I searched on this all search results saying that to get **synced: true** you have to download its full blockchain.  I downloaded **consensus.db** file from https://consensus.siahub.info/ and paste this file in consensus folder and trying to launch SIA daemon its taking too much time to load transaction pool like in below image
![siadresult](https://user-images.githubusercontent.com/29701194/43449097-3913bf52-94cd-11e8-8df9-153a5bfbef6a.png)
I am not getting why this is taking lots of time please help me on this.

**Comment by lukechampine** [comment]
"download the blockchain" doesn't mean you have to download a specific file from a site. If you just wait, siad will download the blockchain from your peers automatically. Downloading consensus.db directly is just faster.

When you downloaded consensus.db, you got a copy of the blockchain. But the other siad "modules" (transaction pool, wallet, renter, etc.) still need to process that blockchain. So your first load will take a while because the modules are processing 100k blocks all at once.

After it finishes loading the first time, subsequent loads will be much faster.

**Comment by snehap007** [comment]
@lukechampine thanks for replying.
