### ISSUE TITLE
gpu miner

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#325]
Josh has offered to help with the GPU mining in Sia, and he was wondering what that might look like.

We could integrate the gpu code into the miner module, or we could make the gpu code a completely separate package/repo/library entirely that we import in the miner module.

Initially I was leaning towards using a separate repo, but now I'm thinking he could just PR into the current mining code. We could split the files into cpumine.go and gpumine.go, and have some higher level logic that figures out which one to use. Or maybe just plain refuses to mine if you don't have a gpu.

I do believe that we'll have to use cgo to get gpu mining working, and we'll also have to use cgo to get the signature library working properly as well, which means we'll probably need to figure out how to get cgo compiling at some point.

**Comment by lukechampine** [comment]
I think the issue with GPU mining is that then you need to support a variety of cards. At the very least you need one for NVIDIA and one for AMD, but you'd probably need to get even more specific. So instead of trying to do GPU mining in-house, I figured that the miner package would just contain a simple CPU miner and some sort of generic interface that any mining executable could hook into. I believe this is how Bitcoin does it -- I recall downloading a separate binary to enable GPU mining -- but I'm not 100% sure.

Now that I think of it, this would be pretty easy to do thanks to our API. Just add two new calls, `/miner/target` and `/miner/submit`. Then you have, say a GPU mining executable, that asks for the current target hash (and any other required info) with `/miner/target`, solves for it, and then submits the solution by calling `/miner/submit`.

**Comment by JoshVorick** [comment]
It looks like OpenCL makes it easy to access and use GPUs. There might need to be a slightly different implementation for AMD and NVIDIA (I don't think so, but AMD only talks about AMD OpenCL and NVIDIA only talks about NVIDIA OpenCL). 
Later on, optimizations could be added that take advantage of GPU-specific feature, but that's a ways away.

As for cgo, I found a Go wrapper for OpenCL, https://godoc.org/github.com/samuel/go-opencl/cl , that might remove the need to do cgo.

For now I'll start working on making something in a seperate repository. I don't know how hard it will be or how  long it will take, though.

**Comment by Kroese** [comment]
Why would you need to look go C wrappers or OpenCL wrappers? It will be incredibly hard to write the whole miner in Go. It would be much simpler to just communicate through websockets or http with the miner instead of nasty interop calls.

**Comment by lukechampine** [comment]
@Kroese, agreed (see my comment above). The miner will be a separate binary, so it can be written in any language desired. It could still be written in Go, but it might be cleaner to just use pure C.

**Comment by Kroese** [comment]
Is the API for this already finished? Because I could hack together a GPU miner pretty fast

**Comment by lukechampine** [comment]
Not yet; it isn't high on the priority list. I'd like to get it out in a month or two. In the meantime, you can assume the existence of the necessary API calls. Speaking of which, what do you think those should be? `/miner/submit/` is pretty obvious for submitting completed blocks, but in order to mine properly, the miner needs to know both the current target and the contents of the block to be mined (including the transaction set, which may be updated during mining).

For reference, [this is how blocks are hashed](https://github.com/NebulousLabs/Sia/blob/master/consensus/types.go#L373). To save the miner the trouble of encoding, it looks like the API call should send the block's `ParentID` and `MerkleRoot()`, and let the miner fill in the nonce.

**Comment by Kroese** [comment]
With Bitcoin a miner doesnt need to know the contents (transactions) in a block, just the header is enough for hashing? Is this different with Sia?

**Comment by DavidVorick** [comment]
it is not, you just need to know the header.

**Comment by Kroese** [comment]
Would be better if the POW is done on the total block in Sia, this makes mining harder for asics. Also, why not use the storage-proofs for mining?

**Comment by DavidVorick** [comment]
https://download.wpsoftware.net/bitcoin/asic-faq.pdf

In general, we like to follow the principles of this document. This would tend towards having the smallest possible block headers, and hashing the least possible data.

**Comment by lukechampine** [comment]
Implemented in http://github.com/NebulousLabs/Sia-GPU-Miner
