### ISSUE TITLE
Anti-cheat

### ISSUE THREAD

**Issue by kroese** [NebulousLabs/Sia#400]
There is a very interesting atomic scheme (that PayFile and PayPub also use), it goes like this:

- A Sia client wants to download a file
- The host deduces a Sia-coin private key from the file hash
- The Sia client sends fees to the to the adress of that key
- The Sia host hashes the public key to get a secret, and encrypts the file
- The Sia client can download this encrypted file for free from the host
- If the host spends from that address means he *must* reveal the public key. 
- Revealing the public key means he reveals the encryption secret for the file, and the client is happy.
- If the host does not spend the coins, the TX is cancelled with a timelock, and nobody is harmed.

**Comment by DavidVorick** [comment]
I don't quite see the use for this scheme., nor do I see how it's secure.

First, the person doing the encryption is the host. For everything we're currently doing, it's the client that does the encryption. Second, if the client is downloading an encrypted file, how can they be sure that they're getting the file they paid for? What if the host uses some other key to encrypt the file?

I guess this is useful for enforcing that the client pay if the client wants to decrypt the file, but I think there are other better ways of achieving this (micropayments)

**Comment by Kroese** [comment]
They can be sure they get the file they pay for, by requestion the host to send the decryption key for 1 small random chunk after they downloaded the full encrypted file. If that chunk turns out to be the file they expected (and the host cannot know which chunk you would ask), they can be pretty sure that the rest of the file will be too.

This is usefull for releasing the key for one download to many people at once.

**Comment by DavidVorick** [comment]
I do not believe that the cheating you are concerned about is possible in our current implementation.
