### ISSUE TITLE
Different default ports for developer constants

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#413]
I like :9980 and :9981 for release ports. I'm not sure why they are 8 apart right now.

Perhaps the developer ports can be :9982 and :9983, or maybe :9990 and :9991. But it would be nice to be able to run a live node and a dev node at the same time without needing to keep a configuration file around.

**Comment by lukechampine** [comment]
:9988 was the original RPC port, chosen mostly at random. :9980 was chosen for the API because :80 is the classic HTTP port.

IMHO you should just run your "live" node on a different port using cmd flags. No need for a config file. Since the live node is (presumably) running for a while, it's not a big deal to pass in the extra args. Setting the default ports via build tags would be gross.

**Comment by DavidVorick** [comment]
Now that we're setting up a testnet, we're probably going to want different default ports for the testnet too.

Or some system that makes it relatively painless to run a bunch of nodes from one computer - developer, testnet, and prodnet nodes. All three are important to developers.
