### ISSUE TITLE
Logging strategy

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#424]
each module should have it's own logger, and should write to a file inside of its directory.

**Comment by lukechampine** [comment]
adding to this, I've found that the mutex conventions apply equally well to logging. Basically, you should only log in functions that lock. In my experience this leads to more descriptive logging (e.g. "Adding new inbound connection localhost:9981 to node list" instead of "added localhost:9981 to node list")

**Comment by lukechampine** [comment]
A logging package is probably warranted at some point. The biggest win would be a `log.Debug` function which would only print during testing, and a `log.Fatal` which would panic during testing but otherwise just log the error. We could also formally define `Info` and `Warn` methods instead of manually appending `"INFO:"` and `"WARN:"` to the log messages.
