### ISSUE TITLE
Cannot restart siad?

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#436]
I get a 'connection refused' error the second time I try to run siad. I think the db has something to do with it.

**Comment by lukechampine** [comment]
loading the db seems to take a non-trivial amount of time, and since the modules need to be initialized before the API becomes available, siad will be unresponsive until the db has been fully loaded.
an easy fix would be to load the db in a goroutine, though I'm not sure what will happen if you receive a block from a peer while doing so.

**Comment by DavidVorick** [comment]
I think that I was running into a different issue.

It all seems better now. It can take a few seconds to startup but that's not terrible.
