### ISSUE TITLE
100% Crypto package coverage

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#511]
merkle.go and hash.go are missing code coverage in the crypto unit tests.

We should correct this.

**Comment by lukechampine** [comment]
I don't think we can get to 100% because I don't see a way to force `rand.Read` to return an error. But we can get pretty close.

I also noticed that `SignHash` returns an error, even though no error is possible. It's left over from when keys were pointers and you had to check for nil. We can probably remove it now.

**Comment by DavidVorick** [comment]
fixed in #552
