### ISSUE TITLE
Issue from slack [Moderate]

### ISSUE THREAD

**Issue by whitj00** [NebulousLabs/Sia#526]
rj134a [8:16 AM] 
I'm trying to send sia coins from my 0.3.0 wallet to an address on the updated 0.3.2. I'm sending over 2 million and says error transaction too large

rj134a [8:17 AM] 
Yet the balance reflects the 2 million coins being taken out

rj134a [8:17 AM]
when i restart the client the 2 million are back

**Comment by DavidVorick** [comment]
We discussed this in the slack, but the problem is that the wallet currently doesn't check if the transaction it is creating has exceeded the 16kb transaction size limit set by the IsStandard() rules.

If it is, there will be an error and the wallet will be seemingly helpless. The fix is to have the wallet make multiple transactions, and then combine the outputs using a final transaction. This isn't a simple fix.

I'll try to have this finished by the June 7th release.

**Comment by DavidVorick** [comment]
:'( never got to it
