### ISSUE TITLE
Wallet output selection algorithm + testing

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#760]
In the wallet, the output selection algorithm is more naive than it needs to be. The current algorithm sorts outputs by size and then selects outputs from biggest to smallest until a high enough balance has been reached.

For smaller sends, this can result in picking large outputs when a smaller output would be sufficient. A lookahead should be implemented that will avoid choosing a large output if a smaller output is sufficient.

Relevant files:

modules/wallet/transactionbuilder.go (FundSiacoins and FundSiafunds)
a modules/wallet/transactionbuilder_test.go should also be created. Bonus points if you can refactor the file - it's kind of messy.

**Comment by mtlynch** [comment]
I want to make sure I'm understanding correctly. It sounds like we want to optimize first for fewest outputs (in quantity), then for lowest outputs (in value).

If we have available outputs with these amounts:

```
[12, 5, 2, 2, 2, 1]
```

Are these the correct outputs to select given different sample fund amounts?

Sample fund amount: `1`
Desired outputs selected: `[1]`

Sample fund amount: `2`
Desired outputs selected: `[2]`

Sample fund amount: `3`
Desired outputs selected: `[5]`
(choose single value rather than two smaller, more exact values)

Sample fund amount: `4`
Desired outputs selected: `[5]`

Sample fund amount: `5`
Desired outputs selected: `[5]`

Sample fund amount: `6`
Desired outputs selected: `[5, 1]`

Sample fund amount: `12`
Desired outputs selected: `[12]`

Does overspend factor into it at all? For example, in my example for `3`, we're choosing `[5]` so that we minimize number of outputs, but it means we require a refund of 2, as opposed to `[2, 1]` which would require no refund.

**Comment by DavidVorick** [comment]
We want to optimize to make the transaction as small as possible. One difference:

Sample fund amount: `6`
Desired outputs selected: `[12]`

This is because each input needs some number of signatures, and signatures take a lot of space. Inputs also take more space than outputs even without the signatures. (Outputs tend to be around 60 bytes, inputs tend to be around 100. Transaction signatures tend to be around 150 bytes - I am only estimating).

So we prioritize minimizing the inputs even over eliminating the need for a refund. Also, in the vast majority of cases there will be a refund because, thanks to file storage, output amounts tend to be highly uneven.

**Comment by mtlynch** [comment]
Cool, gotcha
