### ISSUE TITLE
IP Address Blacklisting in Hostdb

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#761]
There are a few ip addresses that should be blacklisted from the hostdb. Specifically, localhost needs to be blacklisted. Any lan addresses should probably also be blacklisted (10.x.x.x, 192.168.x.x, etc.).

Relevant files:

modules/hostdb/hostentry.go
modules/hostdb/hostentry_test.go

**Comment by lukechampine** [comment]
To clarify, it's okay if the hostdb contacts itself; the problem is contacting yourself multiple times. Worst case, you could wind up forming contracts with `[external IP]`, `[local IP`], `localhost`, `127.0.0.1`, and `[::1]`. We really only want to use the external IP.

A fairly comprehensive blacklist would be:
```
# IPv4 private addresses
10.0.0.0/8
192.168.0.0/16
172.16.0.0/12

# IPv6 private addresses
[fd00::/8]

# loopback address
127.0.0.1
[::1]
localhost
```

Alternatively, we could ban only the loopback addresses, and intelligently determine whether a local address is our own. Sample code to do this exists [here](http://stackoverflow.com/questions/23558425/how-do-i-get-the-local-ip-address-in-go).

The issue of local addresses is relevant to both the hostdb and the gateway. It makes sense that you'd want to connect to locally networked computers; those connections are fast and highly reliable. However, we would like to avoid sharing these addresses externally. It's an open question.

**Comment by DavidVorick** [comment]
I'm pretty sure 127.*.*.* is all localhost. So you could in theory talk to yourself thousands of times.

**Comment by DavidVorick** [comment]
This is ~fixed now
