### ISSUE TITLE
Recieved invalid host address

### ISSUE THREAD

**Issue by chargr** [NebulousLabs/Sia#790]
````
2015/09/09 21:06:41.391973 rpc.go:115: WARN: incoming RPC "RelayNod" failed: address is not routable: <html>
<head>
<title>Web Page Blocked</title>
<style>
body{:9981
````

**Comment by lukechampine** [comment]
wow...that is pretty bizarre. I believe what happened is that the GET request to `myexternalip.com` failed because the page was blocked by a local firewall. Normally this would be caught by `Announce` (attempting to ping the address above would obviously fail), but many users simple use the `--force` flag to ignore any such errors.
This could be improved by checking the StatusCode of the HTTP response in `myExternalIP()`. I imagine it would not be 200 in the case above.
