### ISSUE TITLE
Ignoring errors with the blank identifier

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#883]
Contrary to the developers conventions, there a quite a few places where errors are ignored using the blank identifier (use `errcheck -blank` to find them). In some places these are accompanied by an explanation, e.g. [crypto/encrypt.go](https://github.com/NebulousLabs/Sia/blob/f3272113464e8f4b71383c71978aed400b4dfd89/crypto/encrypt.go#L38-L39)
```go
// NOTE: NewCipher only returns an error if len(key) != 16, 24, or 32.
cipher, _ := twofish.NewCipher(key[:])
```
In others there is no explanation.

Not checking errors if we can safely assume none will occur is not the best but with a valid explanation it seems okay. But for every error ignored (that has an explanation) there should be a corresponding test to make sure that the assumption is true. In this case the test should verify that `len(key)` is 16, 24, or 32.

**Comment by VoidingWarranties** [comment]
Then again it would be simpler and more consistent if errors are never ignored.

**Comment by VoidingWarranties** [comment]
But then `TwofishKey.NewReader` and `TwofishKey.NewWriter` would have to return the errors too. So testing each assumption used to explain why an error is ignored seems like the better solution.

**Comment by DavidVorick** [comment]
Yeah we've been back and forth on this a few times. If your function is already returning an error, then there's almost no excuse, with the exception of defer statements which can be annoying.

`defer obj.Close()` -> can return an error, but how do you check an error inside of a defer statement?

And, if we start enforcing that everything needs to be returning errors, that's pretty annoying especially when the behavior is clear that errors will never be returned. Then again, always checking anyway helps catch developer mistakes.

I think I'd rather have the functions start to return errors. Idk how much headache that will end up being though.

**Comment by lukechampine** [comment]
IIRC the `NewReader` and `NewWriter` functions aren't used anywhere anymore. Originally they were used for encrypting streams (during upload/download), but now we break things into small in-memory chunks anyway so we use `EncryptBytes` instead.

`defer` is usually employed to clean up resources like files and network connections. In most of these cases we don't care if an error is returned. For example, if we've read an input file to `EOF` and processed all its data, an error returned by `Close` is inconsequential (and errors when closing a read-only file seem to be exceedingly rare). Same applies if we've read everything we need from a network connection. There's basically one instance where we might want to check `Close`, and that's when writing to persistent storage. Caching behavior on certain files systems (notably NFS) can cause write errors to only surface when `Close` is called (i.e. when the cache is flushed). So I suggest that if we change anything, we change the handling of `file.Close` in three places: 1) in `persist.SaveFile`, 2) in the host when writing contract data to disk, and 3) in the renter when downloading a file. I think this should cover pretty much all the places where data loss could occur.

In general I'm in favor of rigorous error handling, but I think a practical approach has to be more sophisticated than "propagate every error returned by any function." In the examples I gave above, you wouldn't want to propagate those errors, because the operation didn't actually fail (that is, the function accomplished what it was supposed to). So I narrow it down with two questions: 1) should this error actually impact control flow? and 2) will this function ever produce an error when used in this context? For the former, I recommend adding a comment, and possibly logging the error if it seems prudent to do so. For the latter, I recommend adding a comment and writing tests to assert that the assumption is correct, as you've done in d8e4281.

**Comment by DavidVorick** [comment]
but that still doesn't address how we should handle the actual `errcheck` program, because there are definitely places in the codebase where we should be checking errors and we aren't, and errcheck helps to highlight them. We need some way to let errcheck ignore the errors we don't care about.

errcheck does have a `-ignore` flag, but I'm not sure how to use it.

**Comment by VoidingWarranties** [comment]
I made a change to errcheck that allows you to ignore ignored errors that have a comment above them that starts with a prefix. For example `errcheck -ignorecomment ERRCHECK_IGNORE` would ignore the following line.
``` go
// ERRCHECK_IGNORE: NewCipher only returns an error if len(key) != 16, 24, or 32.
cipher, _ := twofish.NewCipher(key[:])
```
I need to clean it up a bit and then I'll submit a PR to errcheck.

I'll look into adding a flag to ignore errors in defer statements as well.

**Comment by DavidVorick** [comment]
I'd rather use `ERRCHECK_IGNORE` in a comment then intentionally ignore all defers. Some of those deferred statements really do need their errors checked.

What do you mean by `I made a change`? Did you alter the source code? If so, it definitely doesn't hurt to make a PR on the upstream branch of errcheck, the maintainer might even have some better ideas about how to implement it after he sees the code.

**Comment by VoidingWarranties** [comment]
Yup, here's the PR: https://github.com/kisielk/errcheck/pull/86

**Comment by lukechampine** [comment]
Are we planning to make the build fail unless the errcheck is totally clean? How many errors would we need to fix/comment in order for that to happen?

**Comment by DavidVorick** [comment]
Yep, definitely planning on doing that. 292 hits on errcheck as of today. If we go package-by-package, it shouldn't be so bad.

**Comment by DavidVorick** [comment]
vs. 101 hits on golint with min_confidence=1.0

**Comment by VoidingWarranties** [comment]
Make sure to run errcheck with the `-blank` and `-asserts` flags. With those flags I get 356 errors.
