### ISSUE TITLE
Native Go API

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/Sia#901]
Similar to Nodejs-Sia, we should have a package that exposes simple functions for interacting with siad. These would essentially be type-safe wrappers around the HTTP API. siac is already (mostly) doing this, but abstracting it out would allow other people to more easily develop Sia-based applications in Go. And of course, we would reuse it ourselves in siac, such that siac is concerned *only* with command-line interaction, not the details of Sia's HTTP API.

This could be done in a new repo, new package, or inside the api package. I am learning towards the third option; keeping this code close to the existing API code seems like a good idea, and it seems natural for users to import the package as `api`. Perhaps each function could even be physically adjacent to its corresponding handler.

**Comment by DavidVorick** [comment]
Makes sense to be in the Sia repo to me

**Comment by VoidingWarranties** [comment]
It seems very roundabout to wrap the HTTP API in go functions since the call stack would be:
```
func --> HTTP --> func(s)
^^^^ wrapper
         ^^^^ API
                  ^^^^^^^ handler that calls one or more sia functions
```

The only reason the sia functions can't be called directly in the first place is because potentially multiple of them need to be called per API call. In other words, the API surface is defined in the handler methods.

If instead the API surface were defined in go, they could be called directly instead of wrapping the HTTP API. This would make the call stack look like:
```
HTTP API --> go API --> func(s)
```

It also seems more flexible to define the API surface in go so that additional API's can be exposed, e.g. unix sockets.

**Comment by lukechampine** [comment]
That's a good point, but there's a problem: the functions exposed by the modules don't always have the type signatures we want (they may take more arguments than the API allows). Also, you'd have to wire everything up yourself, and the functions are all scattered across half a dozen separate packages.
Consolidating all the API functions in one place allows you to simplify things. But I think we can still partially implement your suggestion; the call chain would look like:
```
HTTP route --> Go API func --> internal module method
```
