### ISSUE TITLE
siac recursive directory upload

### ISSUE THREAD

**Issue by DavidVorick** [NebulousLabs/Sia#913]
siac should have a command that will upload an entire directory

**Comment by lukechampine** [comment]
hmm. I suppose uploading a folder is common enough behavior that we could expect most frontends to support it, hence the justification for doing it on the backend.
We could support this without changing the API, just detect if the source path is a folder and branch on that.
There are a few annoying edge cases here that we would need to manage carefully. I can think of three off the bat: 1) dotfiles, 2) empty folders, 3) directory loops (via symlink). We'd probably include dotfiles by default and add a flag for excluding them. Can't do much about empty folders for now. At least Sia-UI can fake an empty folder, but if its offloading the word to the backend, it won't know which folders to fake. And lastly, we'd need to ensure our `filepath.Walk` detects loops somehow.

**Comment by VoidingWarranties** [comment]
I think symlinks should be ignored by default, with an option to follow them potentially added as a feature in the future. This is `cp`'s and other filesystem utils default behavior.

**Comment by DavidVorick** [comment]
I'm pretty sure filepath.Walk avoids symlinks automatically as well. It's default behavior is probably sane enough that it'll do all the edge cases we need properly.

**Comment by DavidVorick** [comment]
would like to see this following the shortlist for 1.0. It might have to wait, but we should have this done in 1.1 if it's not done by 1.0.

**Comment by VoidingWarranties** [comment]
@johnathanhowell and I were talking about this. Specifically about the expected behavior when you do not have enough space to upload the entire directory. It would be helpful to have a check at the beginning to see if there is enough space to upload the entire directory, and to fail if there is not enough space. Otherwise it would not be obvious to the user which files were successfully uploaded, especially if the directory has a high branching factor or deep branches.

**Comment by DavidVorick** [comment]
Seems reasonable to scan the whole directory before doing any uploading.

**Comment by lukechampine** [comment]
added in https://github.com/NebulousLabs/Sia/pull/1677
