### ISSUE TITLE
siac renter upload and download CLI inconsistencies

### ISSUE THREAD

**Issue by VoidingWarranties** [NebulousLabs/Sia#931]
`siac renter upload [file] [path]` returns immediately and adds the file to the upload queue, but `siac renter download [path] [file]` waits for the file to download before returning, but you can use `siac renter queue` in another window to show the download queue. The mismatched behaviors of the two commands is jarring. Either upload should behave like download or vice-versa.

Furthermore “queue” and “list” are confusing because they both represent files being transferred, but “queue” means downloading files and “list” means uploading files. There is nothing intrinsic to a queue that implies downloading, so lets make the commands match. I propose changing it to `siac renter list download` and `siac renter list upload` or `siac renter list` for both.

Finally, on a somewhat related note, most siac commands have a status command, but renter does not. From the perspective of someone using siac for the first time, I expected a status command. With this in mind I think the renter CLI for getting the status of uploads and downloads should be `siac renter status download`, `siac renter status upload`, and `siac renter status` (instead of `siac renter list download/upload`).

**Comment by lukechampine** [comment]
it's tricky because a download has a clear end point (the file can be opened), but an upload doesn't ever really "complete" -- it just gets added to the repair pool. I suppose we could poll until the file reached availability.

`list` doesn't mean uploading files, it means all files. It just also happens to show files whose uploads haven't completed.

As for `status`, I think we should follow in the footsteps of the API and replace `siac [module] status` with just `siac [module]`

**Comment by lukechampine** [comment]
it also occurred to me that synchronous calls are a little deceptive, since they give the impression that you can cancel the action with Ctrl-C. Since this isn't the case, maybe asynchronous-by-default is best.
