### ISSUE TITLE
Sia stuck at block 33412

### ISSUE THREAD

**Issue by mtlynch** [NebulousLabs/Sia#996]
I'm trying to run Sia on my RasPi 2 B+ and it's been stuck for days at block 33,412. `siad` pegs my CPU and uses about 60% of the system's RAM.

Any way to debug what it's hanging on? I'm running from master at d461e3422695f4f0f047972b1b1d17649f62bcfa.

**Comment by DavidVorick** [comment]
So, we're actively working on this. We believe that the core problem is highly inefficient network usage, which consumes both RAM and stalls out network connections. There was a recently merged PR to prevent siad from broadcasting blocks during IBD, which should help with a lot of the traffic problems. A PR is open right now to flood block headers across the network instead of full blocks, which should also help.

There's another problem where clients will actually do 5+ simultaneously block downloads, meaning they download all of the blocks multiple times over.

We're not sure the exact reason that clients are getting stuck, but Jordan is working on it full time right now. We've made several improvements, expanded testing, and once the remaining obscene inefficiencies are gone we'll add logging and diagnose the freezing (assuming that the freezing isn't solved at that point).

The peering code that's currently in place was only designed to handle tiny blocks and relatively low peer counts. Now that blocks are larger and there are more peers, it's simply not keeping up. Also, there are more blocks, which is contributing to the issues. 

Usually, when it gets stuck it'll get unstuck after a while. Sometimes it's 3 hours, sometimes it's like 18. I'm guessing it's taking you multiple days because the raspi is so low-power. But, Sia in theory should run fine on a raspi. I'm guessing that after we've made the network upgrades, the raspi will do much better. Already we've seen RAM requirements drop about 400MB.

**Comment by mtlynch** [comment]
Left it running for 2 days and I'm up to 35,744. Getting there!

But even if I catch up, can I serve as a functional host node if I'm frequently stuck on blocks for hours/days?

**Comment by DavidVorick** [comment]
People tend to have significantly less trouble once they are caught up. If you are not caught up, you spawn a bunch of goroutines every time there's a block that asks a bunch of peers for all the remaining blocks you are missing, and they'll give them to you, on top of all the ones that you are already downloading from... the same peers. So you get a  ton of concurrent communication that's redundant and completely unnecessary.

Once you are caught up, you stop spawning new threads because you aren't confused about the new blocks. Nodes are usually significantly better at staying caught up than they are at catching up.

**Comment by VoidingWarranties** [comment]
Restarting said may help you catch up faster. I found a bug in the synchronization code today that may be the cause of this. Will have a PR in for the fix later tonight.

**Comment by mtlynch** [comment]
It was making slow progress for a while and now it's been stuck on 38,610 for I think two days now. I tried checking out sync-bug-fix before it got merged and rebuilt and ran with that, but still seeing the issue. I'll re-sync and rebuild.

**Comment by DavidVorick** [comment]
the sync bug fixed one of two issues. Things should be a lot smoother after that merge, but there's another thing that needs to be merged. (limiting the number of peers you are doing IBD with).

**Comment by mtlynch** [comment]
Finally caught up! Whee!

```
$ $GOPATH/bin/siac
Block:  00000000000005ee21c9bfa8c19eed129583f1a7aaf593035eebdd1fe427a7bf
Height: 40071
Target: [0 0 0 0 0 1 99 98 52 169 83 213 45 227 127 200 23 168 24 17 17 144 175 1 193 22 9 247 50 159 229 65]
```
